#region copyright
// (C) Copyright 2015 Dinu Marius-Constantin (http://dinu.at) and others.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Contributors:
//     Dinu Marius-Constantin
#endregion
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using UFO.Server.Bll.Common;
using UFO.Server.Bll.Impl;
using UFO.Server.Common;
using UFO.Server.Domain;

namespace UFO.Server.Test
{
    [TestClass]
    public class ServerBllTests
    {
        private static readonly IBllProviderFactory BllFactory = FactoryProvider.GetFactory<IBllProviderFactory>(BllProviderSettings.Instance);
        private static readonly AAdminAccessBll AdminAccessBll = BllFactory.CreateAAdminAccessBll();
        private static readonly AViewAccessBll ViewAccessBll = BllFactory.CreateAViewAccessBll();
        private static readonly User User = new User
        {
            EMail = "marius.dinu@mymail.com",
            Password = "password"
        };
        private static readonly SessionToken Token = AdminAccessBll.RequestSessionToken(User);
        
        [TestMethod]
        public void TestArtistBllGetAll()
        {
            var viewAccessBll = new ViewAccessBll();
            var list = viewAccessBll.GetArtists(viewAccessBll.RequestArtistPagingData());
            Assert.IsNotNull(list);
            Assert.IsTrue(list.Count > 0);
        }

        [TestMethod]
        public void TestAdminAuthentication()
        {
            Assert.IsFalse(AdminAccessBll.IsUserAuthenticated(Token));
            AdminAccessBll.LoginAdmin(Token);
            Assert.IsTrue(AdminAccessBll.IsUserAuthenticated(Token));
            AdminAccessBll.LogoutAdmin(Token);
            Assert.IsFalse(AdminAccessBll.IsUserAuthenticated(Token));
        }

        [TestMethod]
        public void TestMailNotification()
        {
            Assert.IsTrue(AdminAccessBll.LoginAdmin(Token));
            var notification = new Notification
            {
                Sender = "marius.dinu@mymail.com",
                Recipient = "dinu.marius-constantin@hotmail.com",
                Subject = "Autogenerated",
                Body = "Do not reply!"
            };
            Assert.IsTrue(AdminAccessBll.SendNotification(Token, notification));
        }
    }
}
