
package at.fhooe.hgb.wea5.ufo.web.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ViewAccessWs", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ViewAccessWs {


    /**
     * 
     * @return
     *     returns at.fhooe.hgb.wea5.ufo.web.client.PagingData
     */
    @WebMethod(operationName = "RequestArtistPagingData", action = "http://tempuri.org/ViewAccessWs/RequestArtistPagingData")
    @WebResult(name = "RequestArtistPagingDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RequestArtistPagingData", targetNamespace = "http://tempuri.org/", className = "at.fhooe.hgb.wea5.ufo.web.client.RequestArtistPagingData")
    @ResponseWrapper(localName = "RequestArtistPagingDataResponse", targetNamespace = "http://tempuri.org/", className = "at.fhooe.hgb.wea5.ufo.web.client.RequestArtistPagingDataResponse")
    public PagingData requestArtistPagingData();

    /**
     * 
     * @return
     *     returns at.fhooe.hgb.wea5.ufo.web.client.PagingData
     */
    @WebMethod(operationName = "RequestCategoryPagingData", action = "http://tempuri.org/ViewAccessWs/RequestCategoryPagingData")
    @WebResult(name = "RequestCategoryPagingDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RequestCategoryPagingData", targetNamespace = "http://tempuri.org/", className = "at.fhooe.hgb.wea5.ufo.web.client.RequestCategoryPagingData")
    @ResponseWrapper(localName = "RequestCategoryPagingDataResponse", targetNamespace = "http://tempuri.org/", className = "at.fhooe.hgb.wea5.ufo.web.client.RequestCategoryPagingDataResponse")
    public PagingData requestCategoryPagingData();

    /**
     * 
     * @return
     *     returns at.fhooe.hgb.wea5.ufo.web.client.PagingData
     */
    @WebMethod(operationName = "RequestCountryPagingData", action = "http://tempuri.org/ViewAccessWs/RequestCountryPagingData")
    @WebResult(name = "RequestCountryPagingDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RequestCountryPagingData", targetNamespace = "http://tempuri.org/", className = "at.fhooe.hgb.wea5.ufo.web.client.RequestCountryPagingData")
    @ResponseWrapper(localName = "RequestCountryPagingDataResponse", targetNamespace = "http://tempuri.org/", className = "at.fhooe.hgb.wea5.ufo.web.client.RequestCountryPagingDataResponse")
    public PagingData requestCountryPagingData();

    /**
     * 
     * @return
     *     returns at.fhooe.hgb.wea5.ufo.web.client.PagingData
     */
    @WebMethod(operationName = "RequestLocationPagingData", action = "http://tempuri.org/ViewAccessWs/RequestLocationPagingData")
    @WebResult(name = "RequestLocationPagingDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RequestLocationPagingData", targetNamespace = "http://tempuri.org/", className = "at.fhooe.hgb.wea5.ufo.web.client.RequestLocationPagingData")
    @ResponseWrapper(localName = "RequestLocationPagingDataResponse", targetNamespace = "http://tempuri.org/", className = "at.fhooe.hgb.wea5.ufo.web.client.RequestLocationPagingDataResponse")
    public PagingData requestLocationPagingData();

    /**
     * 
     * @return
     *     returns at.fhooe.hgb.wea5.ufo.web.client.PagingData
     */
    @WebMethod(operationName = "RequestPerformancePagingData", action = "http://tempuri.org/ViewAccessWs/RequestPerformancePagingData")
    @WebResult(name = "RequestPerformancePagingDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RequestPerformancePagingData", targetNamespace = "http://tempuri.org/", className = "at.fhooe.hgb.wea5.ufo.web.client.RequestPerformancePagingData")
    @ResponseWrapper(localName = "RequestPerformancePagingDataResponse", targetNamespace = "http://tempuri.org/", className = "at.fhooe.hgb.wea5.ufo.web.client.RequestPerformancePagingDataResponse")
    public PagingData requestPerformancePagingData();

    /**
     * 
     * @return
     *     returns at.fhooe.hgb.wea5.ufo.web.client.PagingData
     */
    @WebMethod(operationName = "RequestVenuePagingData", action = "http://tempuri.org/ViewAccessWs/RequestVenuePagingData")
    @WebResult(name = "RequestVenuePagingDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RequestVenuePagingData", targetNamespace = "http://tempuri.org/", className = "at.fhooe.hgb.wea5.ufo.web.client.RequestVenuePagingData")
    @ResponseWrapper(localName = "RequestVenuePagingDataResponse", targetNamespace = "http://tempuri.org/", className = "at.fhooe.hgb.wea5.ufo.web.client.RequestVenuePagingDataResponse")
    public PagingData requestVenuePagingData();

    /**
     * 
     * @param page
     * @return
     *     returns at.fhooe.hgb.wea5.ufo.web.client.ArrayOfArtist
     */
    @WebMethod(operationName = "GetArtist", action = "http://tempuri.org/ViewAccessWs/GetArtist")
    @WebResult(name = "GetArtistResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetArtist", targetNamespace = "http://tempuri.org/", className = "at.fhooe.hgb.wea5.ufo.web.client.GetArtist")
    @ResponseWrapper(localName = "GetArtistResponse", targetNamespace = "http://tempuri.org/", className = "at.fhooe.hgb.wea5.ufo.web.client.GetArtistResponse")
    public ArrayOfArtist getArtist(
        @WebParam(name = "page", targetNamespace = "http://tempuri.org/")
        PagingData page);

    /**
     * 
     * @param date
     * @return
     *     returns at.fhooe.hgb.wea5.ufo.web.client.ArrayOfPerformance
     */
    @WebMethod(operationName = "GetPerformancesPerDate", action = "http://tempuri.org/ViewAccessWs/GetPerformancesPerDate")
    @WebResult(name = "GetPerformancesPerDateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPerformancesPerDate", targetNamespace = "http://tempuri.org/", className = "at.fhooe.hgb.wea5.ufo.web.client.GetPerformancesPerDate")
    @ResponseWrapper(localName = "GetPerformancesPerDateResponse", targetNamespace = "http://tempuri.org/", className = "at.fhooe.hgb.wea5.ufo.web.client.GetPerformancesPerDateResponse")
    public ArrayOfPerformance getPerformancesPerDate(
        @WebParam(name = "date", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar date);

    /**
     * 
     * @param page
     * @return
     *     returns at.fhooe.hgb.wea5.ufo.web.client.ArrayOfCategory
     */
    @WebMethod(operationName = "GetCategories", action = "http://tempuri.org/ViewAccessWs/GetCategories")
    @WebResult(name = "GetCategoriesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCategories", targetNamespace = "http://tempuri.org/", className = "at.fhooe.hgb.wea5.ufo.web.client.GetCategories")
    @ResponseWrapper(localName = "GetCategoriesResponse", targetNamespace = "http://tempuri.org/", className = "at.fhooe.hgb.wea5.ufo.web.client.GetCategoriesResponse")
    public ArrayOfCategory getCategories(
        @WebParam(name = "page", targetNamespace = "http://tempuri.org/")
        PagingData page);

    /**
     * 
     * @param page
     * @return
     *     returns at.fhooe.hgb.wea5.ufo.web.client.ArrayOfCountry
     */
    @WebMethod(operationName = "GetCountries", action = "http://tempuri.org/ViewAccessWs/GetCountries")
    @WebResult(name = "GetCountriesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCountries", targetNamespace = "http://tempuri.org/", className = "at.fhooe.hgb.wea5.ufo.web.client.GetCountries")
    @ResponseWrapper(localName = "GetCountriesResponse", targetNamespace = "http://tempuri.org/", className = "at.fhooe.hgb.wea5.ufo.web.client.GetCountriesResponse")
    public ArrayOfCountry getCountries(
        @WebParam(name = "page", targetNamespace = "http://tempuri.org/")
        PagingData page);

    /**
     * 
     * @param page
     * @return
     *     returns at.fhooe.hgb.wea5.ufo.web.client.ArrayOfLocation
     */
    @WebMethod(operationName = "GetLocations", action = "http://tempuri.org/ViewAccessWs/GetLocations")
    @WebResult(name = "GetLocationsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetLocations", targetNamespace = "http://tempuri.org/", className = "at.fhooe.hgb.wea5.ufo.web.client.GetLocations")
    @ResponseWrapper(localName = "GetLocationsResponse", targetNamespace = "http://tempuri.org/", className = "at.fhooe.hgb.wea5.ufo.web.client.GetLocationsResponse")
    public ArrayOfLocation getLocations(
        @WebParam(name = "page", targetNamespace = "http://tempuri.org/")
        PagingData page);

    /**
     * 
     * @param page
     * @return
     *     returns at.fhooe.hgb.wea5.ufo.web.client.ArrayOfVenue
     */
    @WebMethod(operationName = "GetVenues", action = "http://tempuri.org/ViewAccessWs/GetVenues")
    @WebResult(name = "GetVenuesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetVenues", targetNamespace = "http://tempuri.org/", className = "at.fhooe.hgb.wea5.ufo.web.client.GetVenues")
    @ResponseWrapper(localName = "GetVenuesResponse", targetNamespace = "http://tempuri.org/", className = "at.fhooe.hgb.wea5.ufo.web.client.GetVenuesResponse")
    public ArrayOfVenue getVenues(
        @WebParam(name = "page", targetNamespace = "http://tempuri.org/")
        PagingData page);

    /**
     * 
     * @param page
     * @return
     *     returns at.fhooe.hgb.wea5.ufo.web.client.ArrayOfPerformance
     */
    @WebMethod(operationName = "GetPerformances", action = "http://tempuri.org/ViewAccessWs/GetPerformances")
    @WebResult(name = "GetPerformancesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPerformances", targetNamespace = "http://tempuri.org/", className = "at.fhooe.hgb.wea5.ufo.web.client.GetPerformances")
    @ResponseWrapper(localName = "GetPerformancesResponse", targetNamespace = "http://tempuri.org/", className = "at.fhooe.hgb.wea5.ufo.web.client.GetPerformancesResponse")
    public ArrayOfPerformance getPerformances(
        @WebParam(name = "page", targetNamespace = "http://tempuri.org/")
        PagingData page);

}
