
package at.fhooe.hgb.wea5.ufo.web.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ViewAccessWs", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://localhost:4321/ViewAccess?wsdl")
public class ViewAccessWs_Service
    extends Service
{

    private final static URL VIEWACCESSWS_WSDL_LOCATION;
    private final static WebServiceException VIEWACCESSWS_EXCEPTION;
    private final static QName VIEWACCESSWS_QNAME = new QName("http://tempuri.org/", "ViewAccessWs");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:4321/ViewAccess?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VIEWACCESSWS_WSDL_LOCATION = url;
        VIEWACCESSWS_EXCEPTION = e;
    }

    public ViewAccessWs_Service() {
        super(__getWsdlLocation(), VIEWACCESSWS_QNAME);
    }

    public ViewAccessWs_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), VIEWACCESSWS_QNAME, features);
    }

    public ViewAccessWs_Service(URL wsdlLocation) {
        super(wsdlLocation, VIEWACCESSWS_QNAME);
    }

    public ViewAccessWs_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VIEWACCESSWS_QNAME, features);
    }

    public ViewAccessWs_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ViewAccessWs_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ViewAccessWs
     */
    @WebEndpoint(name = "WSHttpBinding_ViewAccessWs")
    public ViewAccessWs getWSHttpBindingViewAccessWs() {
        return super.getPort(new QName("http://tempuri.org/", "WSHttpBinding_ViewAccessWs"), ViewAccessWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ViewAccessWs
     */
    @WebEndpoint(name = "WSHttpBinding_ViewAccessWs")
    public ViewAccessWs getWSHttpBindingViewAccessWs(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "WSHttpBinding_ViewAccessWs"), ViewAccessWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VIEWACCESSWS_EXCEPTION!= null) {
            throw VIEWACCESSWS_EXCEPTION;
        }
        return VIEWACCESSWS_WSDL_LOCATION;
    }

}
