//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UFO.Services.AdminAccess {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DomainObject", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFO.Services.AdminAccess.Artist))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFO.Services.AdminAccess.Category))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFO.Services.AdminAccess.Country))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFO.Services.AdminAccess.BlobData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFO.Services.AdminAccess.Performance))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFO.Services.AdminAccess.Venue))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFO.Services.AdminAccess.Location))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFO.Services.AdminAccess.SessionToken))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFO.Services.AdminAccess.User))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFO.Services.AdminAccess.Notification))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFO.Services.AdminAccess.PagingData))]
    public partial class DomainObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Artist", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class Artist : UFO.Services.AdminAccess.DomainObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ArtistIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UFO.Services.AdminAccess.Category CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UFO.Services.AdminAccess.Country CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UFO.Services.AdminAccess.BlobData PictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PromoVideoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ArtistId {
            get {
                return this.ArtistIdField;
            }
            set {
                if ((this.ArtistIdField.Equals(value) != true)) {
                    this.ArtistIdField = value;
                    this.RaisePropertyChanged("ArtistId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFO.Services.AdminAccess.Category Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFO.Services.AdminAccess.Country Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMail {
            get {
                return this.EMailField;
            }
            set {
                if ((object.ReferenceEquals(this.EMailField, value) != true)) {
                    this.EMailField = value;
                    this.RaisePropertyChanged("EMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFO.Services.AdminAccess.BlobData Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PromoVideo {
            get {
                return this.PromoVideoField;
            }
            set {
                if ((object.ReferenceEquals(this.PromoVideoField, value) != true)) {
                    this.PromoVideoField = value;
                    this.RaisePropertyChanged("PromoVideo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class Category : UFO.Services.AdminAccess.DomainObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryIdField, value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Country", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class Country : UFO.Services.AdminAccess.DomainObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BlobData", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class BlobData : UFO.Services.AdminAccess.DomainObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DataStreamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PathField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] DataStream {
            get {
                return this.DataStreamField;
            }
            set {
                if ((object.ReferenceEquals(this.DataStreamField, value) != true)) {
                    this.DataStreamField = value;
                    this.RaisePropertyChanged("DataStream");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path {
            get {
                return this.PathField;
            }
            set {
                if ((object.ReferenceEquals(this.PathField, value) != true)) {
                    this.PathField = value;
                    this.RaisePropertyChanged("Path");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Performance", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class Performance : UFO.Services.AdminAccess.DomainObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UFO.Services.AdminAccess.Artist ArtistField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UFO.Services.AdminAccess.Venue VenueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFO.Services.AdminAccess.Artist Artist {
            get {
                return this.ArtistField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtistField, value) != true)) {
                    this.ArtistField = value;
                    this.RaisePropertyChanged("Artist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime {
            get {
                return this.DateTimeField;
            }
            set {
                if ((this.DateTimeField.Equals(value) != true)) {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFO.Services.AdminAccess.Venue Venue {
            get {
                return this.VenueField;
            }
            set {
                if ((object.ReferenceEquals(this.VenueField, value) != true)) {
                    this.VenueField = value;
                    this.RaisePropertyChanged("Venue");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Venue", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class Venue : UFO.Services.AdminAccess.DomainObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UFO.Services.AdminAccess.Location LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VenueIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFO.Services.AdminAccess.Location Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VenueId {
            get {
                return this.VenueIdField;
            }
            set {
                if ((object.ReferenceEquals(this.VenueIdField, value) != true)) {
                    this.VenueIdField = value;
                    this.RaisePropertyChanged("VenueId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Location", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class Location : UFO.Services.AdminAccess.DomainObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LocationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LocationId {
            get {
                return this.LocationIdField;
            }
            set {
                if ((this.LocationIdField.Equals(value) != true)) {
                    this.LocationIdField = value;
                    this.RaisePropertyChanged("LocationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SessionToken", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class SessionToken : UFO.Services.AdminAccess.DomainObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char[] SessionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UFO.Services.AdminAccess.User UserField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char[] SessionId {
            get {
                return this.SessionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionIdField, value) != true)) {
                    this.SessionIdField = value;
                    this.RaisePropertyChanged("SessionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFO.Services.AdminAccess.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class User : UFO.Services.AdminAccess.DomainObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UFO.Services.AdminAccess.Artist ArtistField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsArtistField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFO.Services.AdminAccess.Artist Artist {
            get {
                return this.ArtistField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtistField, value) != true)) {
                    this.ArtistField = value;
                    this.RaisePropertyChanged("Artist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMail {
            get {
                return this.EMailField;
            }
            set {
                if ((object.ReferenceEquals(this.EMailField, value) != true)) {
                    this.EMailField = value;
                    this.RaisePropertyChanged("EMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAdmin {
            get {
                return this.IsAdminField;
            }
            set {
                if ((this.IsAdminField.Equals(value) != true)) {
                    this.IsAdminField = value;
                    this.RaisePropertyChanged("IsAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsArtist {
            get {
                return this.IsArtistField;
            }
            set {
                if ((this.IsArtistField.Equals(value) != true)) {
                    this.IsArtistField = value;
                    this.RaisePropertyChanged("IsArtist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Notification", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class Notification : UFO.Services.AdminAccess.DomainObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecipientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Recipient {
            get {
                return this.RecipientField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipientField, value) != true)) {
                    this.RecipientField = value;
                    this.RaisePropertyChanged("Recipient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sender {
            get {
                return this.SenderField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderField, value) != true)) {
                    this.SenderField = value;
                    this.RaisePropertyChanged("Sender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagingData", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class PagingData : UFO.Services.AdminAccess.DomainObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long OffsetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RemainingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SizeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Offset {
            get {
                return this.OffsetField;
            }
            set {
                if ((this.OffsetField.Equals(value) != true)) {
                    this.OffsetField = value;
                    this.RaisePropertyChanged("Offset");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Remaining {
            get {
                return this.RemainingField;
            }
            set {
                if ((this.RemainingField.Equals(value) != true)) {
                    this.RemainingField = value;
                    this.RaisePropertyChanged("Remaining");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Request {
            get {
                return this.RequestField;
            }
            set {
                if ((this.RequestField.Equals(value) != true)) {
                    this.RequestField = value;
                    this.RaisePropertyChanged("Request");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Size {
            get {
                return this.SizeField;
            }
            set {
                if ((this.SizeField.Equals(value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.AdminAccess.ViewAccessWs")]
    public interface ViewAccessWs {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/RequestArtistPagingData", ReplyAction="http://tempuri.org/ViewAccessWs/RequestArtistPagingDataResponse")]
        UFO.Services.AdminAccess.PagingData RequestArtistPagingData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/RequestArtistPagingData", ReplyAction="http://tempuri.org/ViewAccessWs/RequestArtistPagingDataResponse")]
        System.Threading.Tasks.Task<UFO.Services.AdminAccess.PagingData> RequestArtistPagingDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/RequestCategoryPagingData", ReplyAction="http://tempuri.org/ViewAccessWs/RequestCategoryPagingDataResponse")]
        UFO.Services.AdminAccess.PagingData RequestCategoryPagingData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/RequestCategoryPagingData", ReplyAction="http://tempuri.org/ViewAccessWs/RequestCategoryPagingDataResponse")]
        System.Threading.Tasks.Task<UFO.Services.AdminAccess.PagingData> RequestCategoryPagingDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/RequestCountryPagingData", ReplyAction="http://tempuri.org/ViewAccessWs/RequestCountryPagingDataResponse")]
        UFO.Services.AdminAccess.PagingData RequestCountryPagingData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/RequestCountryPagingData", ReplyAction="http://tempuri.org/ViewAccessWs/RequestCountryPagingDataResponse")]
        System.Threading.Tasks.Task<UFO.Services.AdminAccess.PagingData> RequestCountryPagingDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/RequestLocationPagingData", ReplyAction="http://tempuri.org/ViewAccessWs/RequestLocationPagingDataResponse")]
        UFO.Services.AdminAccess.PagingData RequestLocationPagingData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/RequestLocationPagingData", ReplyAction="http://tempuri.org/ViewAccessWs/RequestLocationPagingDataResponse")]
        System.Threading.Tasks.Task<UFO.Services.AdminAccess.PagingData> RequestLocationPagingDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/RequestPerformancePagingData", ReplyAction="http://tempuri.org/ViewAccessWs/RequestPerformancePagingDataResponse")]
        UFO.Services.AdminAccess.PagingData RequestPerformancePagingData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/RequestPerformancePagingData", ReplyAction="http://tempuri.org/ViewAccessWs/RequestPerformancePagingDataResponse")]
        System.Threading.Tasks.Task<UFO.Services.AdminAccess.PagingData> RequestPerformancePagingDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/RequestVenuePagingData", ReplyAction="http://tempuri.org/ViewAccessWs/RequestVenuePagingDataResponse")]
        UFO.Services.AdminAccess.PagingData RequestVenuePagingData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/RequestVenuePagingData", ReplyAction="http://tempuri.org/ViewAccessWs/RequestVenuePagingDataResponse")]
        System.Threading.Tasks.Task<UFO.Services.AdminAccess.PagingData> RequestVenuePagingDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetArtists", ReplyAction="http://tempuri.org/ViewAccessWs/GetArtistsResponse")]
        UFO.Services.AdminAccess.Artist[] GetArtists(UFO.Services.AdminAccess.PagingData page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetArtists", ReplyAction="http://tempuri.org/ViewAccessWs/GetArtistsResponse")]
        System.Threading.Tasks.Task<UFO.Services.AdminAccess.Artist[]> GetArtistsAsync(UFO.Services.AdminAccess.PagingData page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetArtist", ReplyAction="http://tempuri.org/ViewAccessWs/GetArtistResponse")]
        UFO.Services.AdminAccess.Artist GetArtist(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetArtist", ReplyAction="http://tempuri.org/ViewAccessWs/GetArtistResponse")]
        System.Threading.Tasks.Task<UFO.Services.AdminAccess.Artist> GetArtistAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetPerformances", ReplyAction="http://tempuri.org/ViewAccessWs/GetPerformancesResponse")]
        UFO.Services.AdminAccess.Performance[] GetPerformances(UFO.Services.AdminAccess.PagingData page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetPerformances", ReplyAction="http://tempuri.org/ViewAccessWs/GetPerformancesResponse")]
        System.Threading.Tasks.Task<UFO.Services.AdminAccess.Performance[]> GetPerformancesAsync(UFO.Services.AdminAccess.PagingData page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetPerformancesPerDate", ReplyAction="http://tempuri.org/ViewAccessWs/GetPerformancesPerDateResponse")]
        UFO.Services.AdminAccess.Performance[] GetPerformancesPerDate(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetPerformancesPerDate", ReplyAction="http://tempuri.org/ViewAccessWs/GetPerformancesPerDateResponse")]
        System.Threading.Tasks.Task<UFO.Services.AdminAccess.Performance[]> GetPerformancesPerDateAsync(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetPerformancesPerArtist", ReplyAction="http://tempuri.org/ViewAccessWs/GetPerformancesPerArtistResponse")]
        UFO.Services.AdminAccess.Performance[] GetPerformancesPerArtist(UFO.Services.AdminAccess.Artist artist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetPerformancesPerArtist", ReplyAction="http://tempuri.org/ViewAccessWs/GetPerformancesPerArtistResponse")]
        System.Threading.Tasks.Task<UFO.Services.AdminAccess.Performance[]> GetPerformancesPerArtistAsync(UFO.Services.AdminAccess.Artist artist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetPerformancesPerVenue", ReplyAction="http://tempuri.org/ViewAccessWs/GetPerformancesPerVenueResponse")]
        UFO.Services.AdminAccess.Performance[] GetPerformancesPerVenue(UFO.Services.AdminAccess.Venue venue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetPerformancesPerVenue", ReplyAction="http://tempuri.org/ViewAccessWs/GetPerformancesPerVenueResponse")]
        System.Threading.Tasks.Task<UFO.Services.AdminAccess.Performance[]> GetPerformancesPerVenueAsync(UFO.Services.AdminAccess.Venue venue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetLatestPerformances", ReplyAction="http://tempuri.org/ViewAccessWs/GetLatestPerformancesResponse")]
        UFO.Services.AdminAccess.Performance[] GetLatestPerformances();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetLatestPerformances", ReplyAction="http://tempuri.org/ViewAccessWs/GetLatestPerformancesResponse")]
        System.Threading.Tasks.Task<UFO.Services.AdminAccess.Performance[]> GetLatestPerformancesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetCategories", ReplyAction="http://tempuri.org/ViewAccessWs/GetCategoriesResponse")]
        UFO.Services.AdminAccess.Category[] GetCategories(UFO.Services.AdminAccess.PagingData page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetCategories", ReplyAction="http://tempuri.org/ViewAccessWs/GetCategoriesResponse")]
        System.Threading.Tasks.Task<UFO.Services.AdminAccess.Category[]> GetCategoriesAsync(UFO.Services.AdminAccess.PagingData page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetCountries", ReplyAction="http://tempuri.org/ViewAccessWs/GetCountriesResponse")]
        UFO.Services.AdminAccess.Country[] GetCountries(UFO.Services.AdminAccess.PagingData page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetCountries", ReplyAction="http://tempuri.org/ViewAccessWs/GetCountriesResponse")]
        System.Threading.Tasks.Task<UFO.Services.AdminAccess.Country[]> GetCountriesAsync(UFO.Services.AdminAccess.PagingData page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetLocations", ReplyAction="http://tempuri.org/ViewAccessWs/GetLocationsResponse")]
        UFO.Services.AdminAccess.Location[] GetLocations(UFO.Services.AdminAccess.PagingData page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetLocations", ReplyAction="http://tempuri.org/ViewAccessWs/GetLocationsResponse")]
        System.Threading.Tasks.Task<UFO.Services.AdminAccess.Location[]> GetLocationsAsync(UFO.Services.AdminAccess.PagingData page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetVenues", ReplyAction="http://tempuri.org/ViewAccessWs/GetVenuesResponse")]
        UFO.Services.AdminAccess.Venue[] GetVenues(UFO.Services.AdminAccess.PagingData page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetVenues", ReplyAction="http://tempuri.org/ViewAccessWs/GetVenuesResponse")]
        System.Threading.Tasks.Task<UFO.Services.AdminAccess.Venue[]> GetVenuesAsync(UFO.Services.AdminAccess.PagingData page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetVenue", ReplyAction="http://tempuri.org/ViewAccessWs/GetVenueResponse")]
        UFO.Services.AdminAccess.Venue GetVenue(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetVenue", ReplyAction="http://tempuri.org/ViewAccessWs/GetVenueResponse")]
        System.Threading.Tasks.Task<UFO.Services.AdminAccess.Venue> GetVenueAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/SearchPerformancesPerKeyword", ReplyAction="http://tempuri.org/ViewAccessWs/SearchPerformancesPerKeywordResponse")]
        UFO.Services.AdminAccess.Performance[] SearchPerformancesPerKeyword(string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/SearchPerformancesPerKeyword", ReplyAction="http://tempuri.org/ViewAccessWs/SearchPerformancesPerKeywordResponse")]
        System.Threading.Tasks.Task<UFO.Services.AdminAccess.Performance[]> SearchPerformancesPerKeywordAsync(string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/SearchVenuesPerKeyword", ReplyAction="http://tempuri.org/ViewAccessWs/SearchVenuesPerKeywordResponse")]
        UFO.Services.AdminAccess.Venue[] SearchVenuesPerKeyword(string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/SearchVenuesPerKeyword", ReplyAction="http://tempuri.org/ViewAccessWs/SearchVenuesPerKeywordResponse")]
        System.Threading.Tasks.Task<UFO.Services.AdminAccess.Venue[]> SearchVenuesPerKeywordAsync(string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/SearchArtistsPerKeyword", ReplyAction="http://tempuri.org/ViewAccessWs/SearchArtistsPerKeywordResponse")]
        UFO.Services.AdminAccess.Artist[] SearchArtistsPerKeyword(string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/SearchArtistsPerKeyword", ReplyAction="http://tempuri.org/ViewAccessWs/SearchArtistsPerKeywordResponse")]
        System.Threading.Tasks.Task<UFO.Services.AdminAccess.Artist[]> SearchArtistsPerKeywordAsync(string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetAutoPerformanceCompletion", ReplyAction="http://tempuri.org/ViewAccessWs/GetAutoPerformanceCompletionResponse")]
        string[] GetAutoPerformanceCompletion(string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetAutoPerformanceCompletion", ReplyAction="http://tempuri.org/ViewAccessWs/GetAutoPerformanceCompletionResponse")]
        System.Threading.Tasks.Task<string[]> GetAutoPerformanceCompletionAsync(string keyword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ViewAccessWsChannel : UFO.Services.AdminAccess.ViewAccessWs, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ViewAccessWsClient : System.ServiceModel.ClientBase<UFO.Services.AdminAccess.ViewAccessWs>, UFO.Services.AdminAccess.ViewAccessWs {
        
        public ViewAccessWsClient() {
        }
        
        public ViewAccessWsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ViewAccessWsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ViewAccessWsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ViewAccessWsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UFO.Services.AdminAccess.PagingData RequestArtistPagingData() {
            return base.Channel.RequestArtistPagingData();
        }
        
        public System.Threading.Tasks.Task<UFO.Services.AdminAccess.PagingData> RequestArtistPagingDataAsync() {
            return base.Channel.RequestArtistPagingDataAsync();
        }
        
        public UFO.Services.AdminAccess.PagingData RequestCategoryPagingData() {
            return base.Channel.RequestCategoryPagingData();
        }
        
        public System.Threading.Tasks.Task<UFO.Services.AdminAccess.PagingData> RequestCategoryPagingDataAsync() {
            return base.Channel.RequestCategoryPagingDataAsync();
        }
        
        public UFO.Services.AdminAccess.PagingData RequestCountryPagingData() {
            return base.Channel.RequestCountryPagingData();
        }
        
        public System.Threading.Tasks.Task<UFO.Services.AdminAccess.PagingData> RequestCountryPagingDataAsync() {
            return base.Channel.RequestCountryPagingDataAsync();
        }
        
        public UFO.Services.AdminAccess.PagingData RequestLocationPagingData() {
            return base.Channel.RequestLocationPagingData();
        }
        
        public System.Threading.Tasks.Task<UFO.Services.AdminAccess.PagingData> RequestLocationPagingDataAsync() {
            return base.Channel.RequestLocationPagingDataAsync();
        }
        
        public UFO.Services.AdminAccess.PagingData RequestPerformancePagingData() {
            return base.Channel.RequestPerformancePagingData();
        }
        
        public System.Threading.Tasks.Task<UFO.Services.AdminAccess.PagingData> RequestPerformancePagingDataAsync() {
            return base.Channel.RequestPerformancePagingDataAsync();
        }
        
        public UFO.Services.AdminAccess.PagingData RequestVenuePagingData() {
            return base.Channel.RequestVenuePagingData();
        }
        
        public System.Threading.Tasks.Task<UFO.Services.AdminAccess.PagingData> RequestVenuePagingDataAsync() {
            return base.Channel.RequestVenuePagingDataAsync();
        }
        
        public UFO.Services.AdminAccess.Artist[] GetArtists(UFO.Services.AdminAccess.PagingData page) {
            return base.Channel.GetArtists(page);
        }
        
        public System.Threading.Tasks.Task<UFO.Services.AdminAccess.Artist[]> GetArtistsAsync(UFO.Services.AdminAccess.PagingData page) {
            return base.Channel.GetArtistsAsync(page);
        }
        
        public UFO.Services.AdminAccess.Artist GetArtist(int id) {
            return base.Channel.GetArtist(id);
        }
        
        public System.Threading.Tasks.Task<UFO.Services.AdminAccess.Artist> GetArtistAsync(int id) {
            return base.Channel.GetArtistAsync(id);
        }
        
        public UFO.Services.AdminAccess.Performance[] GetPerformances(UFO.Services.AdminAccess.PagingData page) {
            return base.Channel.GetPerformances(page);
        }
        
        public System.Threading.Tasks.Task<UFO.Services.AdminAccess.Performance[]> GetPerformancesAsync(UFO.Services.AdminAccess.PagingData page) {
            return base.Channel.GetPerformancesAsync(page);
        }
        
        public UFO.Services.AdminAccess.Performance[] GetPerformancesPerDate(System.DateTime date) {
            return base.Channel.GetPerformancesPerDate(date);
        }
        
        public System.Threading.Tasks.Task<UFO.Services.AdminAccess.Performance[]> GetPerformancesPerDateAsync(System.DateTime date) {
            return base.Channel.GetPerformancesPerDateAsync(date);
        }
        
        public UFO.Services.AdminAccess.Performance[] GetPerformancesPerArtist(UFO.Services.AdminAccess.Artist artist) {
            return base.Channel.GetPerformancesPerArtist(artist);
        }
        
        public System.Threading.Tasks.Task<UFO.Services.AdminAccess.Performance[]> GetPerformancesPerArtistAsync(UFO.Services.AdminAccess.Artist artist) {
            return base.Channel.GetPerformancesPerArtistAsync(artist);
        }
        
        public UFO.Services.AdminAccess.Performance[] GetPerformancesPerVenue(UFO.Services.AdminAccess.Venue venue) {
            return base.Channel.GetPerformancesPerVenue(venue);
        }
        
        public System.Threading.Tasks.Task<UFO.Services.AdminAccess.Performance[]> GetPerformancesPerVenueAsync(UFO.Services.AdminAccess.Venue venue) {
            return base.Channel.GetPerformancesPerVenueAsync(venue);
        }
        
        public UFO.Services.AdminAccess.Performance[] GetLatestPerformances() {
            return base.Channel.GetLatestPerformances();
        }
        
        public System.Threading.Tasks.Task<UFO.Services.AdminAccess.Performance[]> GetLatestPerformancesAsync() {
            return base.Channel.GetLatestPerformancesAsync();
        }
        
        public UFO.Services.AdminAccess.Category[] GetCategories(UFO.Services.AdminAccess.PagingData page) {
            return base.Channel.GetCategories(page);
        }
        
        public System.Threading.Tasks.Task<UFO.Services.AdminAccess.Category[]> GetCategoriesAsync(UFO.Services.AdminAccess.PagingData page) {
            return base.Channel.GetCategoriesAsync(page);
        }
        
        public UFO.Services.AdminAccess.Country[] GetCountries(UFO.Services.AdminAccess.PagingData page) {
            return base.Channel.GetCountries(page);
        }
        
        public System.Threading.Tasks.Task<UFO.Services.AdminAccess.Country[]> GetCountriesAsync(UFO.Services.AdminAccess.PagingData page) {
            return base.Channel.GetCountriesAsync(page);
        }
        
        public UFO.Services.AdminAccess.Location[] GetLocations(UFO.Services.AdminAccess.PagingData page) {
            return base.Channel.GetLocations(page);
        }
        
        public System.Threading.Tasks.Task<UFO.Services.AdminAccess.Location[]> GetLocationsAsync(UFO.Services.AdminAccess.PagingData page) {
            return base.Channel.GetLocationsAsync(page);
        }
        
        public UFO.Services.AdminAccess.Venue[] GetVenues(UFO.Services.AdminAccess.PagingData page) {
            return base.Channel.GetVenues(page);
        }
        
        public System.Threading.Tasks.Task<UFO.Services.AdminAccess.Venue[]> GetVenuesAsync(UFO.Services.AdminAccess.PagingData page) {
            return base.Channel.GetVenuesAsync(page);
        }
        
        public UFO.Services.AdminAccess.Venue GetVenue(string id) {
            return base.Channel.GetVenue(id);
        }
        
        public System.Threading.Tasks.Task<UFO.Services.AdminAccess.Venue> GetVenueAsync(string id) {
            return base.Channel.GetVenueAsync(id);
        }
        
        public UFO.Services.AdminAccess.Performance[] SearchPerformancesPerKeyword(string keyword) {
            return base.Channel.SearchPerformancesPerKeyword(keyword);
        }
        
        public System.Threading.Tasks.Task<UFO.Services.AdminAccess.Performance[]> SearchPerformancesPerKeywordAsync(string keyword) {
            return base.Channel.SearchPerformancesPerKeywordAsync(keyword);
        }
        
        public UFO.Services.AdminAccess.Venue[] SearchVenuesPerKeyword(string keyword) {
            return base.Channel.SearchVenuesPerKeyword(keyword);
        }
        
        public System.Threading.Tasks.Task<UFO.Services.AdminAccess.Venue[]> SearchVenuesPerKeywordAsync(string keyword) {
            return base.Channel.SearchVenuesPerKeywordAsync(keyword);
        }
        
        public UFO.Services.AdminAccess.Artist[] SearchArtistsPerKeyword(string keyword) {
            return base.Channel.SearchArtistsPerKeyword(keyword);
        }
        
        public System.Threading.Tasks.Task<UFO.Services.AdminAccess.Artist[]> SearchArtistsPerKeywordAsync(string keyword) {
            return base.Channel.SearchArtistsPerKeywordAsync(keyword);
        }
        
        public string[] GetAutoPerformanceCompletion(string keyword) {
            return base.Channel.GetAutoPerformanceCompletion(keyword);
        }
        
        public System.Threading.Tasks.Task<string[]> GetAutoPerformanceCompletionAsync(string keyword) {
            return base.Channel.GetAutoPerformanceCompletionAsync(keyword);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.AdminAccess.AdminAccessWs")]
    public interface AdminAccessWs {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/ModifyArtistRange", ReplyAction="http://tempuri.org/AdminAccessWs/ModifyArtistRangeResponse")]
        bool ModifyArtistRange(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Artist[] artists);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/ModifyArtistRange", ReplyAction="http://tempuri.org/AdminAccessWs/ModifyArtistRangeResponse")]
        System.Threading.Tasks.Task<bool> ModifyArtistRangeAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Artist[] artists);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/RemovePerformance", ReplyAction="http://tempuri.org/AdminAccessWs/RemovePerformanceResponse")]
        bool RemovePerformance(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Performance performance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/RemovePerformance", ReplyAction="http://tempuri.org/AdminAccessWs/RemovePerformanceResponse")]
        System.Threading.Tasks.Task<bool> RemovePerformanceAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Performance performance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/ModifyLocationRange", ReplyAction="http://tempuri.org/AdminAccessWs/ModifyLocationRangeResponse")]
        bool ModifyLocationRange(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Location[] locations);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/ModifyLocationRange", ReplyAction="http://tempuri.org/AdminAccessWs/ModifyLocationRangeResponse")]
        System.Threading.Tasks.Task<bool> ModifyLocationRangeAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Location[] locations);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/ModifyLocation", ReplyAction="http://tempuri.org/AdminAccessWs/ModifyLocationResponse")]
        bool ModifyLocation(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Location location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/ModifyLocation", ReplyAction="http://tempuri.org/AdminAccessWs/ModifyLocationResponse")]
        System.Threading.Tasks.Task<bool> ModifyLocationAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Location location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/RemoveLocation", ReplyAction="http://tempuri.org/AdminAccessWs/RemoveLocationResponse")]
        bool RemoveLocation(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Location location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/RemoveLocation", ReplyAction="http://tempuri.org/AdminAccessWs/RemoveLocationResponse")]
        System.Threading.Tasks.Task<bool> RemoveLocationAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Location location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/ModifyVenueRange", ReplyAction="http://tempuri.org/AdminAccessWs/ModifyVenueRangeResponse")]
        bool ModifyVenueRange(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Venue[] venues);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/ModifyVenueRange", ReplyAction="http://tempuri.org/AdminAccessWs/ModifyVenueRangeResponse")]
        System.Threading.Tasks.Task<bool> ModifyVenueRangeAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Venue[] venues);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/ModifyPerformanceRange", ReplyAction="http://tempuri.org/AdminAccessWs/ModifyPerformanceRangeResponse")]
        bool ModifyPerformanceRange(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Performance[] performances);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/ModifyPerformanceRange", ReplyAction="http://tempuri.org/AdminAccessWs/ModifyPerformanceRangeResponse")]
        System.Threading.Tasks.Task<bool> ModifyPerformanceRangeAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Performance[] performances);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/DelayPerformance", ReplyAction="http://tempuri.org/AdminAccessWs/DelayPerformanceResponse")]
        bool DelayPerformance(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Performance oldPerformance, UFO.Services.AdminAccess.Performance newPerformance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/DelayPerformance", ReplyAction="http://tempuri.org/AdminAccessWs/DelayPerformanceResponse")]
        System.Threading.Tasks.Task<bool> DelayPerformanceAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Performance oldPerformance, UFO.Services.AdminAccess.Performance newPerformance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/GetUsers", ReplyAction="http://tempuri.org/AdminAccessWs/GetUsersResponse")]
        UFO.Services.AdminAccess.User[] GetUsers(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.PagingData page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/GetUsers", ReplyAction="http://tempuri.org/AdminAccessWs/GetUsersResponse")]
        System.Threading.Tasks.Task<UFO.Services.AdminAccess.User[]> GetUsersAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.PagingData page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/SearchUsersPerKeyword", ReplyAction="http://tempuri.org/AdminAccessWs/SearchUsersPerKeywordResponse")]
        UFO.Services.AdminAccess.User[] SearchUsersPerKeyword(UFO.Services.AdminAccess.SessionToken token, string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/SearchUsersPerKeyword", ReplyAction="http://tempuri.org/AdminAccessWs/SearchUsersPerKeywordResponse")]
        System.Threading.Tasks.Task<UFO.Services.AdminAccess.User[]> SearchUsersPerKeywordAsync(UFO.Services.AdminAccess.SessionToken token, string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/GetUserAutoCompletion", ReplyAction="http://tempuri.org/AdminAccessWs/GetUserAutoCompletionResponse")]
        string[] GetUserAutoCompletion(UFO.Services.AdminAccess.SessionToken token, string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/GetUserAutoCompletion", ReplyAction="http://tempuri.org/AdminAccessWs/GetUserAutoCompletionResponse")]
        System.Threading.Tasks.Task<string[]> GetUserAutoCompletionAsync(UFO.Services.AdminAccess.SessionToken token, string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/RequestUserPagingData", ReplyAction="http://tempuri.org/AdminAccessWs/RequestUserPagingDataResponse")]
        UFO.Services.AdminAccess.PagingData RequestUserPagingData(UFO.Services.AdminAccess.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/RequestUserPagingData", ReplyAction="http://tempuri.org/AdminAccessWs/RequestUserPagingDataResponse")]
        System.Threading.Tasks.Task<UFO.Services.AdminAccess.PagingData> RequestUserPagingDataAsync(UFO.Services.AdminAccess.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/IsUserAuthenticated", ReplyAction="http://tempuri.org/AdminAccessWs/IsUserAuthenticatedResponse")]
        bool IsUserAuthenticated(UFO.Services.AdminAccess.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/IsUserAuthenticated", ReplyAction="http://tempuri.org/AdminAccessWs/IsUserAuthenticatedResponse")]
        System.Threading.Tasks.Task<bool> IsUserAuthenticatedAsync(UFO.Services.AdminAccess.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/IsValidAdmin", ReplyAction="http://tempuri.org/AdminAccessWs/IsValidAdminResponse")]
        bool IsValidAdmin(UFO.Services.AdminAccess.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/IsValidAdmin", ReplyAction="http://tempuri.org/AdminAccessWs/IsValidAdminResponse")]
        System.Threading.Tasks.Task<bool> IsValidAdminAsync(UFO.Services.AdminAccess.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/LoginAdmin", ReplyAction="http://tempuri.org/AdminAccessWs/LoginAdminResponse")]
        bool LoginAdmin(UFO.Services.AdminAccess.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/LoginAdmin", ReplyAction="http://tempuri.org/AdminAccessWs/LoginAdminResponse")]
        System.Threading.Tasks.Task<bool> LoginAdminAsync(UFO.Services.AdminAccess.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/LogoutAdmin", ReplyAction="http://tempuri.org/AdminAccessWs/LogoutAdminResponse")]
        void LogoutAdmin(UFO.Services.AdminAccess.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/LogoutAdmin", ReplyAction="http://tempuri.org/AdminAccessWs/LogoutAdminResponse")]
        System.Threading.Tasks.Task LogoutAdminAsync(UFO.Services.AdminAccess.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/RequestSessionToken", ReplyAction="http://tempuri.org/AdminAccessWs/RequestSessionTokenResponse")]
        UFO.Services.AdminAccess.SessionToken RequestSessionToken(UFO.Services.AdminAccess.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/RequestSessionToken", ReplyAction="http://tempuri.org/AdminAccessWs/RequestSessionTokenResponse")]
        System.Threading.Tasks.Task<UFO.Services.AdminAccess.SessionToken> RequestSessionTokenAsync(UFO.Services.AdminAccess.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/ModifyArtist", ReplyAction="http://tempuri.org/AdminAccessWs/ModifyArtistResponse")]
        bool ModifyArtist(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Artist artist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/ModifyArtist", ReplyAction="http://tempuri.org/AdminAccessWs/ModifyArtistResponse")]
        System.Threading.Tasks.Task<bool> ModifyArtistAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Artist artist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/RemoveArtist", ReplyAction="http://tempuri.org/AdminAccessWs/RemoveArtistResponse")]
        bool RemoveArtist(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Artist artist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/RemoveArtist", ReplyAction="http://tempuri.org/AdminAccessWs/RemoveArtistResponse")]
        System.Threading.Tasks.Task<bool> RemoveArtistAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Artist artist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/ModifyVenue", ReplyAction="http://tempuri.org/AdminAccessWs/ModifyVenueResponse")]
        bool ModifyVenue(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Venue venue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/ModifyVenue", ReplyAction="http://tempuri.org/AdminAccessWs/ModifyVenueResponse")]
        System.Threading.Tasks.Task<bool> ModifyVenueAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Venue venue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/RemoveVenue", ReplyAction="http://tempuri.org/AdminAccessWs/RemoveVenueResponse")]
        bool RemoveVenue(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Venue venue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/RemoveVenue", ReplyAction="http://tempuri.org/AdminAccessWs/RemoveVenueResponse")]
        System.Threading.Tasks.Task<bool> RemoveVenueAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Venue venue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/ModifyPerformance", ReplyAction="http://tempuri.org/AdminAccessWs/ModifyPerformanceResponse")]
        bool ModifyPerformance(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Performance performance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/ModifyPerformance", ReplyAction="http://tempuri.org/AdminAccessWs/ModifyPerformanceResponse")]
        System.Threading.Tasks.Task<bool> ModifyPerformanceAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Performance performance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/SendNotification", ReplyAction="http://tempuri.org/AdminAccessWs/SendNotificationResponse")]
        bool SendNotification(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Notification notification);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/SendNotification", ReplyAction="http://tempuri.org/AdminAccessWs/SendNotificationResponse")]
        System.Threading.Tasks.Task<bool> SendNotificationAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Notification notification);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AdminAccessWsChannel : UFO.Services.AdminAccess.AdminAccessWs, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminAccessWsClient : System.ServiceModel.ClientBase<UFO.Services.AdminAccess.AdminAccessWs>, UFO.Services.AdminAccess.AdminAccessWs {
        
        public AdminAccessWsClient() {
        }
        
        public AdminAccessWsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminAccessWsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminAccessWsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminAccessWsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ModifyArtistRange(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Artist[] artists) {
            return base.Channel.ModifyArtistRange(token, artists);
        }
        
        public System.Threading.Tasks.Task<bool> ModifyArtistRangeAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Artist[] artists) {
            return base.Channel.ModifyArtistRangeAsync(token, artists);
        }
        
        public bool RemovePerformance(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Performance performance) {
            return base.Channel.RemovePerformance(token, performance);
        }
        
        public System.Threading.Tasks.Task<bool> RemovePerformanceAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Performance performance) {
            return base.Channel.RemovePerformanceAsync(token, performance);
        }
        
        public bool ModifyLocationRange(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Location[] locations) {
            return base.Channel.ModifyLocationRange(token, locations);
        }
        
        public System.Threading.Tasks.Task<bool> ModifyLocationRangeAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Location[] locations) {
            return base.Channel.ModifyLocationRangeAsync(token, locations);
        }
        
        public bool ModifyLocation(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Location location) {
            return base.Channel.ModifyLocation(token, location);
        }
        
        public System.Threading.Tasks.Task<bool> ModifyLocationAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Location location) {
            return base.Channel.ModifyLocationAsync(token, location);
        }
        
        public bool RemoveLocation(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Location location) {
            return base.Channel.RemoveLocation(token, location);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveLocationAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Location location) {
            return base.Channel.RemoveLocationAsync(token, location);
        }
        
        public bool ModifyVenueRange(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Venue[] venues) {
            return base.Channel.ModifyVenueRange(token, venues);
        }
        
        public System.Threading.Tasks.Task<bool> ModifyVenueRangeAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Venue[] venues) {
            return base.Channel.ModifyVenueRangeAsync(token, venues);
        }
        
        public bool ModifyPerformanceRange(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Performance[] performances) {
            return base.Channel.ModifyPerformanceRange(token, performances);
        }
        
        public System.Threading.Tasks.Task<bool> ModifyPerformanceRangeAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Performance[] performances) {
            return base.Channel.ModifyPerformanceRangeAsync(token, performances);
        }
        
        public bool DelayPerformance(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Performance oldPerformance, UFO.Services.AdminAccess.Performance newPerformance) {
            return base.Channel.DelayPerformance(token, oldPerformance, newPerformance);
        }
        
        public System.Threading.Tasks.Task<bool> DelayPerformanceAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Performance oldPerformance, UFO.Services.AdminAccess.Performance newPerformance) {
            return base.Channel.DelayPerformanceAsync(token, oldPerformance, newPerformance);
        }
        
        public UFO.Services.AdminAccess.User[] GetUsers(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.PagingData page) {
            return base.Channel.GetUsers(token, page);
        }
        
        public System.Threading.Tasks.Task<UFO.Services.AdminAccess.User[]> GetUsersAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.PagingData page) {
            return base.Channel.GetUsersAsync(token, page);
        }
        
        public UFO.Services.AdminAccess.User[] SearchUsersPerKeyword(UFO.Services.AdminAccess.SessionToken token, string keyword) {
            return base.Channel.SearchUsersPerKeyword(token, keyword);
        }
        
        public System.Threading.Tasks.Task<UFO.Services.AdminAccess.User[]> SearchUsersPerKeywordAsync(UFO.Services.AdminAccess.SessionToken token, string keyword) {
            return base.Channel.SearchUsersPerKeywordAsync(token, keyword);
        }
        
        public string[] GetUserAutoCompletion(UFO.Services.AdminAccess.SessionToken token, string keyword) {
            return base.Channel.GetUserAutoCompletion(token, keyword);
        }
        
        public System.Threading.Tasks.Task<string[]> GetUserAutoCompletionAsync(UFO.Services.AdminAccess.SessionToken token, string keyword) {
            return base.Channel.GetUserAutoCompletionAsync(token, keyword);
        }
        
        public UFO.Services.AdminAccess.PagingData RequestUserPagingData(UFO.Services.AdminAccess.SessionToken token) {
            return base.Channel.RequestUserPagingData(token);
        }
        
        public System.Threading.Tasks.Task<UFO.Services.AdminAccess.PagingData> RequestUserPagingDataAsync(UFO.Services.AdminAccess.SessionToken token) {
            return base.Channel.RequestUserPagingDataAsync(token);
        }
        
        public bool IsUserAuthenticated(UFO.Services.AdminAccess.SessionToken token) {
            return base.Channel.IsUserAuthenticated(token);
        }
        
        public System.Threading.Tasks.Task<bool> IsUserAuthenticatedAsync(UFO.Services.AdminAccess.SessionToken token) {
            return base.Channel.IsUserAuthenticatedAsync(token);
        }
        
        public bool IsValidAdmin(UFO.Services.AdminAccess.SessionToken token) {
            return base.Channel.IsValidAdmin(token);
        }
        
        public System.Threading.Tasks.Task<bool> IsValidAdminAsync(UFO.Services.AdminAccess.SessionToken token) {
            return base.Channel.IsValidAdminAsync(token);
        }
        
        public bool LoginAdmin(UFO.Services.AdminAccess.SessionToken token) {
            return base.Channel.LoginAdmin(token);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAdminAsync(UFO.Services.AdminAccess.SessionToken token) {
            return base.Channel.LoginAdminAsync(token);
        }
        
        public void LogoutAdmin(UFO.Services.AdminAccess.SessionToken token) {
            base.Channel.LogoutAdmin(token);
        }
        
        public System.Threading.Tasks.Task LogoutAdminAsync(UFO.Services.AdminAccess.SessionToken token) {
            return base.Channel.LogoutAdminAsync(token);
        }
        
        public UFO.Services.AdminAccess.SessionToken RequestSessionToken(UFO.Services.AdminAccess.User user) {
            return base.Channel.RequestSessionToken(user);
        }
        
        public System.Threading.Tasks.Task<UFO.Services.AdminAccess.SessionToken> RequestSessionTokenAsync(UFO.Services.AdminAccess.User user) {
            return base.Channel.RequestSessionTokenAsync(user);
        }
        
        public bool ModifyArtist(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Artist artist) {
            return base.Channel.ModifyArtist(token, artist);
        }
        
        public System.Threading.Tasks.Task<bool> ModifyArtistAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Artist artist) {
            return base.Channel.ModifyArtistAsync(token, artist);
        }
        
        public bool RemoveArtist(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Artist artist) {
            return base.Channel.RemoveArtist(token, artist);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveArtistAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Artist artist) {
            return base.Channel.RemoveArtistAsync(token, artist);
        }
        
        public bool ModifyVenue(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Venue venue) {
            return base.Channel.ModifyVenue(token, venue);
        }
        
        public System.Threading.Tasks.Task<bool> ModifyVenueAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Venue venue) {
            return base.Channel.ModifyVenueAsync(token, venue);
        }
        
        public bool RemoveVenue(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Venue venue) {
            return base.Channel.RemoveVenue(token, venue);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveVenueAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Venue venue) {
            return base.Channel.RemoveVenueAsync(token, venue);
        }
        
        public bool ModifyPerformance(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Performance performance) {
            return base.Channel.ModifyPerformance(token, performance);
        }
        
        public System.Threading.Tasks.Task<bool> ModifyPerformanceAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Performance performance) {
            return base.Channel.ModifyPerformanceAsync(token, performance);
        }
        
        public bool SendNotification(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Notification notification) {
            return base.Channel.SendNotification(token, notification);
        }
        
        public System.Threading.Tasks.Task<bool> SendNotificationAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Notification notification) {
            return base.Channel.SendNotificationAsync(token, notification);
        }
    }
}
