//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UFO.Services.AdminAccess {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DomainObject", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFO.Services.AdminAccess.Category))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFO.Services.AdminAccess.Country))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFO.Services.AdminAccess.BlobData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFO.Services.AdminAccess.SessionToken))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFO.Services.AdminAccess.User))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFO.Services.AdminAccess.Artist))]
    public partial class DomainObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class Category : UFO.Services.AdminAccess.DomainObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryIdField, value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Country", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class Country : UFO.Services.AdminAccess.DomainObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BlobData", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class BlobData : UFO.Services.AdminAccess.DomainObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DataStreamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PathField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] DataStream {
            get {
                return this.DataStreamField;
            }
            set {
                if ((object.ReferenceEquals(this.DataStreamField, value) != true)) {
                    this.DataStreamField = value;
                    this.RaisePropertyChanged("DataStream");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path {
            get {
                return this.PathField;
            }
            set {
                if ((object.ReferenceEquals(this.PathField, value) != true)) {
                    this.PathField = value;
                    this.RaisePropertyChanged("Path");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SessionToken", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class SessionToken : UFO.Services.AdminAccess.DomainObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char[] SessionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UFO.Services.AdminAccess.User UserField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char[] SessionId {
            get {
                return this.SessionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionIdField, value) != true)) {
                    this.SessionIdField = value;
                    this.RaisePropertyChanged("SessionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFO.Services.AdminAccess.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class User : UFO.Services.AdminAccess.DomainObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UFO.Services.AdminAccess.Artist ArtistField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsArtistField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFO.Services.AdminAccess.Artist Artist {
            get {
                return this.ArtistField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtistField, value) != true)) {
                    this.ArtistField = value;
                    this.RaisePropertyChanged("Artist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMail {
            get {
                return this.EMailField;
            }
            set {
                if ((object.ReferenceEquals(this.EMailField, value) != true)) {
                    this.EMailField = value;
                    this.RaisePropertyChanged("EMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAdmin {
            get {
                return this.IsAdminField;
            }
            set {
                if ((this.IsAdminField.Equals(value) != true)) {
                    this.IsAdminField = value;
                    this.RaisePropertyChanged("IsAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsArtist {
            get {
                return this.IsArtistField;
            }
            set {
                if ((this.IsArtistField.Equals(value) != true)) {
                    this.IsArtistField = value;
                    this.RaisePropertyChanged("IsArtist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Artist", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class Artist : UFO.Services.AdminAccess.DomainObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ArtistIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UFO.Services.AdminAccess.Category CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UFO.Services.AdminAccess.Country CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UFO.Services.AdminAccess.BlobData PictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PromoVideoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ArtistId {
            get {
                return this.ArtistIdField;
            }
            set {
                if ((this.ArtistIdField.Equals(value) != true)) {
                    this.ArtistIdField = value;
                    this.RaisePropertyChanged("ArtistId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFO.Services.AdminAccess.Category Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFO.Services.AdminAccess.Country Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMail {
            get {
                return this.EMailField;
            }
            set {
                if ((object.ReferenceEquals(this.EMailField, value) != true)) {
                    this.EMailField = value;
                    this.RaisePropertyChanged("EMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFO.Services.AdminAccess.BlobData Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PromoVideo {
            get {
                return this.PromoVideoField;
            }
            set {
                if ((object.ReferenceEquals(this.PromoVideoField, value) != true)) {
                    this.PromoVideoField = value;
                    this.RaisePropertyChanged("PromoVideo");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.AdminAccess.AdminAccessWs")]
    public interface AdminAccessWs {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/InsertArtist", ReplyAction="http://tempuri.org/AdminAccessWs/InsertArtistResponse")]
        void InsertArtist(UFO.Services.AdminAccess.Artist artist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/InsertArtist", ReplyAction="http://tempuri.org/AdminAccessWs/InsertArtistResponse")]
        System.Threading.Tasks.Task InsertArtistAsync(UFO.Services.AdminAccess.Artist artist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/GetAll", ReplyAction="http://tempuri.org/AdminAccessWs/GetAllResponse")]
        UFO.Services.AdminAccess.User[] GetAll(UFO.Services.AdminAccess.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/GetAll", ReplyAction="http://tempuri.org/AdminAccessWs/GetAllResponse")]
        System.Threading.Tasks.Task<UFO.Services.AdminAccess.User[]> GetAllAsync(UFO.Services.AdminAccess.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/IsUserAuthenticated", ReplyAction="http://tempuri.org/AdminAccessWs/IsUserAuthenticatedResponse")]
        bool IsUserAuthenticated(UFO.Services.AdminAccess.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/IsUserAuthenticated", ReplyAction="http://tempuri.org/AdminAccessWs/IsUserAuthenticatedResponse")]
        System.Threading.Tasks.Task<bool> IsUserAuthenticatedAsync(UFO.Services.AdminAccess.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/IsValidAdmin", ReplyAction="http://tempuri.org/AdminAccessWs/IsValidAdminResponse")]
        bool IsValidAdmin(UFO.Services.AdminAccess.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/IsValidAdmin", ReplyAction="http://tempuri.org/AdminAccessWs/IsValidAdminResponse")]
        System.Threading.Tasks.Task<bool> IsValidAdminAsync(UFO.Services.AdminAccess.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/LoginAdmin", ReplyAction="http://tempuri.org/AdminAccessWs/LoginAdminResponse")]
        bool LoginAdmin(UFO.Services.AdminAccess.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/LoginAdmin", ReplyAction="http://tempuri.org/AdminAccessWs/LoginAdminResponse")]
        System.Threading.Tasks.Task<bool> LoginAdminAsync(UFO.Services.AdminAccess.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/LogoutAdmin", ReplyAction="http://tempuri.org/AdminAccessWs/LogoutAdminResponse")]
        void LogoutAdmin(UFO.Services.AdminAccess.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/LogoutAdmin", ReplyAction="http://tempuri.org/AdminAccessWs/LogoutAdminResponse")]
        System.Threading.Tasks.Task LogoutAdminAsync(UFO.Services.AdminAccess.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/RequestSessionToken", ReplyAction="http://tempuri.org/AdminAccessWs/RequestSessionTokenResponse")]
        UFO.Services.AdminAccess.SessionToken RequestSessionToken(UFO.Services.AdminAccess.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/RequestSessionToken", ReplyAction="http://tempuri.org/AdminAccessWs/RequestSessionTokenResponse")]
        System.Threading.Tasks.Task<UFO.Services.AdminAccess.SessionToken> RequestSessionTokenAsync(UFO.Services.AdminAccess.User user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AdminAccessWsChannel : UFO.Services.AdminAccess.AdminAccessWs, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminAccessWsClient : System.ServiceModel.ClientBase<UFO.Services.AdminAccess.AdminAccessWs>, UFO.Services.AdminAccess.AdminAccessWs {
        
        public AdminAccessWsClient() {
        }
        
        public AdminAccessWsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminAccessWsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminAccessWsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminAccessWsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsertArtist(UFO.Services.AdminAccess.Artist artist) {
            base.Channel.InsertArtist(artist);
        }
        
        public System.Threading.Tasks.Task InsertArtistAsync(UFO.Services.AdminAccess.Artist artist) {
            return base.Channel.InsertArtistAsync(artist);
        }
        
        public UFO.Services.AdminAccess.User[] GetAll(UFO.Services.AdminAccess.SessionToken token) {
            return base.Channel.GetAll(token);
        }
        
        public System.Threading.Tasks.Task<UFO.Services.AdminAccess.User[]> GetAllAsync(UFO.Services.AdminAccess.SessionToken token) {
            return base.Channel.GetAllAsync(token);
        }
        
        public bool IsUserAuthenticated(UFO.Services.AdminAccess.SessionToken token) {
            return base.Channel.IsUserAuthenticated(token);
        }
        
        public System.Threading.Tasks.Task<bool> IsUserAuthenticatedAsync(UFO.Services.AdminAccess.SessionToken token) {
            return base.Channel.IsUserAuthenticatedAsync(token);
        }
        
        public bool IsValidAdmin(UFO.Services.AdminAccess.SessionToken token) {
            return base.Channel.IsValidAdmin(token);
        }
        
        public System.Threading.Tasks.Task<bool> IsValidAdminAsync(UFO.Services.AdminAccess.SessionToken token) {
            return base.Channel.IsValidAdminAsync(token);
        }
        
        public bool LoginAdmin(UFO.Services.AdminAccess.SessionToken token) {
            return base.Channel.LoginAdmin(token);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAdminAsync(UFO.Services.AdminAccess.SessionToken token) {
            return base.Channel.LoginAdminAsync(token);
        }
        
        public void LogoutAdmin(UFO.Services.AdminAccess.SessionToken token) {
            base.Channel.LogoutAdmin(token);
        }
        
        public System.Threading.Tasks.Task LogoutAdminAsync(UFO.Services.AdminAccess.SessionToken token) {
            return base.Channel.LogoutAdminAsync(token);
        }
        
        public UFO.Services.AdminAccess.SessionToken RequestSessionToken(UFO.Services.AdminAccess.User user) {
            return base.Channel.RequestSessionToken(user);
        }
        
        public System.Threading.Tasks.Task<UFO.Services.AdminAccess.SessionToken> RequestSessionTokenAsync(UFO.Services.AdminAccess.User user) {
            return base.Channel.RequestSessionTokenAsync(user);
        }
    }
}
