//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UFO.Services.AdminAccess {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DomainObject", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFO.Services.AdminAccess.User))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFO.Services.AdminAccess.Artist))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFO.Services.AdminAccess.Category))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFO.Services.AdminAccess.Country))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFO.Services.AdminAccess.BlobData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFO.Services.AdminAccess.Venue))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFO.Services.AdminAccess.Location))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFO.Services.AdminAccess.Performance))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFO.Services.AdminAccess.PagingData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFO.Services.AdminAccess.SessionToken))]
    public partial class DomainObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class User : UFO.Services.AdminAccess.DomainObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UFO.Services.AdminAccess.Artist ArtistField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsArtistField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFO.Services.AdminAccess.Artist Artist {
            get {
                return this.ArtistField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtistField, value) != true)) {
                    this.ArtistField = value;
                    this.RaisePropertyChanged("Artist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMail {
            get {
                return this.EMailField;
            }
            set {
                if ((object.ReferenceEquals(this.EMailField, value) != true)) {
                    this.EMailField = value;
                    this.RaisePropertyChanged("EMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAdmin {
            get {
                return this.IsAdminField;
            }
            set {
                if ((this.IsAdminField.Equals(value) != true)) {
                    this.IsAdminField = value;
                    this.RaisePropertyChanged("IsAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsArtist {
            get {
                return this.IsArtistField;
            }
            set {
                if ((this.IsArtistField.Equals(value) != true)) {
                    this.IsArtistField = value;
                    this.RaisePropertyChanged("IsArtist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Artist", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class Artist : UFO.Services.AdminAccess.DomainObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ArtistIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UFO.Services.AdminAccess.Category CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UFO.Services.AdminAccess.Country CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UFO.Services.AdminAccess.BlobData PictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PromoVideoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ArtistId {
            get {
                return this.ArtistIdField;
            }
            set {
                if ((this.ArtistIdField.Equals(value) != true)) {
                    this.ArtistIdField = value;
                    this.RaisePropertyChanged("ArtistId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFO.Services.AdminAccess.Category Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFO.Services.AdminAccess.Country Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMail {
            get {
                return this.EMailField;
            }
            set {
                if ((object.ReferenceEquals(this.EMailField, value) != true)) {
                    this.EMailField = value;
                    this.RaisePropertyChanged("EMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFO.Services.AdminAccess.BlobData Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PromoVideo {
            get {
                return this.PromoVideoField;
            }
            set {
                if ((object.ReferenceEquals(this.PromoVideoField, value) != true)) {
                    this.PromoVideoField = value;
                    this.RaisePropertyChanged("PromoVideo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class Category : UFO.Services.AdminAccess.DomainObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryIdField, value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Country", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class Country : UFO.Services.AdminAccess.DomainObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BlobData", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class BlobData : UFO.Services.AdminAccess.DomainObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DataStreamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PathField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] DataStream {
            get {
                return this.DataStreamField;
            }
            set {
                if ((object.ReferenceEquals(this.DataStreamField, value) != true)) {
                    this.DataStreamField = value;
                    this.RaisePropertyChanged("DataStream");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path {
            get {
                return this.PathField;
            }
            set {
                if ((object.ReferenceEquals(this.PathField, value) != true)) {
                    this.PathField = value;
                    this.RaisePropertyChanged("Path");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Venue", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class Venue : UFO.Services.AdminAccess.DomainObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UFO.Services.AdminAccess.Location LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VenueIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFO.Services.AdminAccess.Location Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VenueId {
            get {
                return this.VenueIdField;
            }
            set {
                if ((object.ReferenceEquals(this.VenueIdField, value) != true)) {
                    this.VenueIdField = value;
                    this.RaisePropertyChanged("VenueId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Location", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class Location : UFO.Services.AdminAccess.DomainObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LocationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LocationId {
            get {
                return this.LocationIdField;
            }
            set {
                if ((this.LocationIdField.Equals(value) != true)) {
                    this.LocationIdField = value;
                    this.RaisePropertyChanged("LocationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Performance", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class Performance : UFO.Services.AdminAccess.DomainObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UFO.Services.AdminAccess.Artist ArtistField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UFO.Services.AdminAccess.Venue VenueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFO.Services.AdminAccess.Artist Artist {
            get {
                return this.ArtistField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtistField, value) != true)) {
                    this.ArtistField = value;
                    this.RaisePropertyChanged("Artist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime {
            get {
                return this.DateTimeField;
            }
            set {
                if ((this.DateTimeField.Equals(value) != true)) {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFO.Services.AdminAccess.Venue Venue {
            get {
                return this.VenueField;
            }
            set {
                if ((object.ReferenceEquals(this.VenueField, value) != true)) {
                    this.VenueField = value;
                    this.RaisePropertyChanged("Venue");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagingData", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class PagingData : UFO.Services.AdminAccess.DomainObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long OffsetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RemainingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SizeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Offset {
            get {
                return this.OffsetField;
            }
            set {
                if ((this.OffsetField.Equals(value) != true)) {
                    this.OffsetField = value;
                    this.RaisePropertyChanged("Offset");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Remaining {
            get {
                return this.RemainingField;
            }
            set {
                if ((this.RemainingField.Equals(value) != true)) {
                    this.RemainingField = value;
                    this.RaisePropertyChanged("Remaining");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Request {
            get {
                return this.RequestField;
            }
            set {
                if ((this.RequestField.Equals(value) != true)) {
                    this.RequestField = value;
                    this.RaisePropertyChanged("Request");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Size {
            get {
                return this.SizeField;
            }
            set {
                if ((this.SizeField.Equals(value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SessionToken", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class SessionToken : UFO.Services.AdminAccess.DomainObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char[] SessionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UFO.Services.AdminAccess.User UserField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char[] SessionId {
            get {
                return this.SessionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionIdField, value) != true)) {
                    this.SessionIdField = value;
                    this.RaisePropertyChanged("SessionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFO.Services.AdminAccess.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.AdminAccess.AdminAccessWs")]
    public interface AdminAccessWs {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/ModifyArtistRange", ReplyAction="http://tempuri.org/AdminAccessWs/ModifyArtistRangeResponse")]
        bool ModifyArtistRange(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Artist[] artists);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/ModifyArtistRange", ReplyAction="http://tempuri.org/AdminAccessWs/ModifyArtistRangeResponse")]
        System.Threading.Tasks.Task<bool> ModifyArtistRangeAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Artist[] artists);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/ModifyVenueRange", ReplyAction="http://tempuri.org/AdminAccessWs/ModifyVenueRangeResponse")]
        bool ModifyVenueRange(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Venue[] venues);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/ModifyVenueRange", ReplyAction="http://tempuri.org/AdminAccessWs/ModifyVenueRangeResponse")]
        System.Threading.Tasks.Task<bool> ModifyVenueRangeAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Venue[] venues);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/ModifyPerformanceRange", ReplyAction="http://tempuri.org/AdminAccessWs/ModifyPerformanceRangeResponse")]
        bool ModifyPerformanceRange(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Performance[] performances);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/ModifyPerformanceRange", ReplyAction="http://tempuri.org/AdminAccessWs/ModifyPerformanceRangeResponse")]
        System.Threading.Tasks.Task<bool> ModifyPerformanceRangeAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Performance[] performances);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/GetUser", ReplyAction="http://tempuri.org/AdminAccessWs/GetUserResponse")]
        UFO.Services.AdminAccess.User[] GetUser(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.PagingData page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/GetUser", ReplyAction="http://tempuri.org/AdminAccessWs/GetUserResponse")]
        System.Threading.Tasks.Task<UFO.Services.AdminAccess.User[]> GetUserAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.PagingData page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/RequestUserPagingData", ReplyAction="http://tempuri.org/AdminAccessWs/RequestUserPagingDataResponse")]
        UFO.Services.AdminAccess.PagingData RequestUserPagingData(UFO.Services.AdminAccess.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/RequestUserPagingData", ReplyAction="http://tempuri.org/AdminAccessWs/RequestUserPagingDataResponse")]
        System.Threading.Tasks.Task<UFO.Services.AdminAccess.PagingData> RequestUserPagingDataAsync(UFO.Services.AdminAccess.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/IsUserAuthenticated", ReplyAction="http://tempuri.org/AdminAccessWs/IsUserAuthenticatedResponse")]
        bool IsUserAuthenticated(UFO.Services.AdminAccess.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/IsUserAuthenticated", ReplyAction="http://tempuri.org/AdminAccessWs/IsUserAuthenticatedResponse")]
        System.Threading.Tasks.Task<bool> IsUserAuthenticatedAsync(UFO.Services.AdminAccess.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/IsValidAdmin", ReplyAction="http://tempuri.org/AdminAccessWs/IsValidAdminResponse")]
        bool IsValidAdmin(UFO.Services.AdminAccess.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/IsValidAdmin", ReplyAction="http://tempuri.org/AdminAccessWs/IsValidAdminResponse")]
        System.Threading.Tasks.Task<bool> IsValidAdminAsync(UFO.Services.AdminAccess.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/LoginAdmin", ReplyAction="http://tempuri.org/AdminAccessWs/LoginAdminResponse")]
        bool LoginAdmin(UFO.Services.AdminAccess.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/LoginAdmin", ReplyAction="http://tempuri.org/AdminAccessWs/LoginAdminResponse")]
        System.Threading.Tasks.Task<bool> LoginAdminAsync(UFO.Services.AdminAccess.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/LogoutAdmin", ReplyAction="http://tempuri.org/AdminAccessWs/LogoutAdminResponse")]
        void LogoutAdmin(UFO.Services.AdminAccess.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/LogoutAdmin", ReplyAction="http://tempuri.org/AdminAccessWs/LogoutAdminResponse")]
        System.Threading.Tasks.Task LogoutAdminAsync(UFO.Services.AdminAccess.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/RequestSessionToken", ReplyAction="http://tempuri.org/AdminAccessWs/RequestSessionTokenResponse")]
        UFO.Services.AdminAccess.SessionToken RequestSessionToken(UFO.Services.AdminAccess.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/RequestSessionToken", ReplyAction="http://tempuri.org/AdminAccessWs/RequestSessionTokenResponse")]
        System.Threading.Tasks.Task<UFO.Services.AdminAccess.SessionToken> RequestSessionTokenAsync(UFO.Services.AdminAccess.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/ModifyArtist", ReplyAction="http://tempuri.org/AdminAccessWs/ModifyArtistResponse")]
        bool ModifyArtist(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Artist artist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/ModifyArtist", ReplyAction="http://tempuri.org/AdminAccessWs/ModifyArtistResponse")]
        System.Threading.Tasks.Task<bool> ModifyArtistAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Artist artist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/RemoveArtist", ReplyAction="http://tempuri.org/AdminAccessWs/RemoveArtistResponse")]
        bool RemoveArtist(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Artist artist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/RemoveArtist", ReplyAction="http://tempuri.org/AdminAccessWs/RemoveArtistResponse")]
        System.Threading.Tasks.Task<bool> RemoveArtistAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Artist artist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/ModifyVenue", ReplyAction="http://tempuri.org/AdminAccessWs/ModifyVenueResponse")]
        bool ModifyVenue(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Venue venue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/ModifyVenue", ReplyAction="http://tempuri.org/AdminAccessWs/ModifyVenueResponse")]
        System.Threading.Tasks.Task<bool> ModifyVenueAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Venue venue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/RemoveVenue", ReplyAction="http://tempuri.org/AdminAccessWs/RemoveVenueResponse")]
        bool RemoveVenue(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Venue venue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/RemoveVenue", ReplyAction="http://tempuri.org/AdminAccessWs/RemoveVenueResponse")]
        System.Threading.Tasks.Task<bool> RemoveVenueAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Venue venue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/ModifyPerformance", ReplyAction="http://tempuri.org/AdminAccessWs/ModifyPerformanceResponse")]
        bool ModifyPerformance(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Performance performance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/ModifyPerformance", ReplyAction="http://tempuri.org/AdminAccessWs/ModifyPerformanceResponse")]
        System.Threading.Tasks.Task<bool> ModifyPerformanceAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Performance performance);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AdminAccessWsChannel : UFO.Services.AdminAccess.AdminAccessWs, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminAccessWsClient : System.ServiceModel.ClientBase<UFO.Services.AdminAccess.AdminAccessWs>, UFO.Services.AdminAccess.AdminAccessWs {
        
        public AdminAccessWsClient() {
        }
        
        public AdminAccessWsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminAccessWsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminAccessWsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminAccessWsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ModifyArtistRange(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Artist[] artists) {
            return base.Channel.ModifyArtistRange(token, artists);
        }
        
        public System.Threading.Tasks.Task<bool> ModifyArtistRangeAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Artist[] artists) {
            return base.Channel.ModifyArtistRangeAsync(token, artists);
        }
        
        public bool ModifyVenueRange(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Venue[] venues) {
            return base.Channel.ModifyVenueRange(token, venues);
        }
        
        public System.Threading.Tasks.Task<bool> ModifyVenueRangeAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Venue[] venues) {
            return base.Channel.ModifyVenueRangeAsync(token, venues);
        }
        
        public bool ModifyPerformanceRange(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Performance[] performances) {
            return base.Channel.ModifyPerformanceRange(token, performances);
        }
        
        public System.Threading.Tasks.Task<bool> ModifyPerformanceRangeAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Performance[] performances) {
            return base.Channel.ModifyPerformanceRangeAsync(token, performances);
        }
        
        public UFO.Services.AdminAccess.User[] GetUser(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.PagingData page) {
            return base.Channel.GetUser(token, page);
        }
        
        public System.Threading.Tasks.Task<UFO.Services.AdminAccess.User[]> GetUserAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.PagingData page) {
            return base.Channel.GetUserAsync(token, page);
        }
        
        public UFO.Services.AdminAccess.PagingData RequestUserPagingData(UFO.Services.AdminAccess.SessionToken token) {
            return base.Channel.RequestUserPagingData(token);
        }
        
        public System.Threading.Tasks.Task<UFO.Services.AdminAccess.PagingData> RequestUserPagingDataAsync(UFO.Services.AdminAccess.SessionToken token) {
            return base.Channel.RequestUserPagingDataAsync(token);
        }
        
        public bool IsUserAuthenticated(UFO.Services.AdminAccess.SessionToken token) {
            return base.Channel.IsUserAuthenticated(token);
        }
        
        public System.Threading.Tasks.Task<bool> IsUserAuthenticatedAsync(UFO.Services.AdminAccess.SessionToken token) {
            return base.Channel.IsUserAuthenticatedAsync(token);
        }
        
        public bool IsValidAdmin(UFO.Services.AdminAccess.SessionToken token) {
            return base.Channel.IsValidAdmin(token);
        }
        
        public System.Threading.Tasks.Task<bool> IsValidAdminAsync(UFO.Services.AdminAccess.SessionToken token) {
            return base.Channel.IsValidAdminAsync(token);
        }
        
        public bool LoginAdmin(UFO.Services.AdminAccess.SessionToken token) {
            return base.Channel.LoginAdmin(token);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAdminAsync(UFO.Services.AdminAccess.SessionToken token) {
            return base.Channel.LoginAdminAsync(token);
        }
        
        public void LogoutAdmin(UFO.Services.AdminAccess.SessionToken token) {
            base.Channel.LogoutAdmin(token);
        }
        
        public System.Threading.Tasks.Task LogoutAdminAsync(UFO.Services.AdminAccess.SessionToken token) {
            return base.Channel.LogoutAdminAsync(token);
        }
        
        public UFO.Services.AdminAccess.SessionToken RequestSessionToken(UFO.Services.AdminAccess.User user) {
            return base.Channel.RequestSessionToken(user);
        }
        
        public System.Threading.Tasks.Task<UFO.Services.AdminAccess.SessionToken> RequestSessionTokenAsync(UFO.Services.AdminAccess.User user) {
            return base.Channel.RequestSessionTokenAsync(user);
        }
        
        public bool ModifyArtist(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Artist artist) {
            return base.Channel.ModifyArtist(token, artist);
        }
        
        public System.Threading.Tasks.Task<bool> ModifyArtistAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Artist artist) {
            return base.Channel.ModifyArtistAsync(token, artist);
        }
        
        public bool RemoveArtist(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Artist artist) {
            return base.Channel.RemoveArtist(token, artist);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveArtistAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Artist artist) {
            return base.Channel.RemoveArtistAsync(token, artist);
        }
        
        public bool ModifyVenue(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Venue venue) {
            return base.Channel.ModifyVenue(token, venue);
        }
        
        public System.Threading.Tasks.Task<bool> ModifyVenueAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Venue venue) {
            return base.Channel.ModifyVenueAsync(token, venue);
        }
        
        public bool RemoveVenue(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Venue venue) {
            return base.Channel.RemoveVenue(token, venue);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveVenueAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Venue venue) {
            return base.Channel.RemoveVenueAsync(token, venue);
        }
        
        public bool ModifyPerformance(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Performance performance) {
            return base.Channel.ModifyPerformance(token, performance);
        }
        
        public System.Threading.Tasks.Task<bool> ModifyPerformanceAsync(UFO.Services.AdminAccess.SessionToken token, UFO.Services.AdminAccess.Performance performance) {
            return base.Channel.ModifyPerformanceAsync(token, performance);
        }
    }
}
