//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UFO.Services.ViewAccess {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DomainObject", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFO.Services.ViewAccess.Artist))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFO.Services.ViewAccess.Category))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFO.Services.ViewAccess.Country))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFO.Services.ViewAccess.BlobData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFO.Services.ViewAccess.Performance))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFO.Services.ViewAccess.Venue))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFO.Services.ViewAccess.Location))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFO.Services.ViewAccess.PagingData))]
    public partial class DomainObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Artist", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class Artist : UFO.Services.ViewAccess.DomainObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ArtistIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UFO.Services.ViewAccess.Category CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UFO.Services.ViewAccess.Country CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UFO.Services.ViewAccess.BlobData PictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PromoVideoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ArtistId {
            get {
                return this.ArtistIdField;
            }
            set {
                if ((this.ArtistIdField.Equals(value) != true)) {
                    this.ArtistIdField = value;
                    this.RaisePropertyChanged("ArtistId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFO.Services.ViewAccess.Category Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFO.Services.ViewAccess.Country Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMail {
            get {
                return this.EMailField;
            }
            set {
                if ((object.ReferenceEquals(this.EMailField, value) != true)) {
                    this.EMailField = value;
                    this.RaisePropertyChanged("EMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFO.Services.ViewAccess.BlobData Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PromoVideo {
            get {
                return this.PromoVideoField;
            }
            set {
                if ((object.ReferenceEquals(this.PromoVideoField, value) != true)) {
                    this.PromoVideoField = value;
                    this.RaisePropertyChanged("PromoVideo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class Category : UFO.Services.ViewAccess.DomainObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryIdField, value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Country", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class Country : UFO.Services.ViewAccess.DomainObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BlobData", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class BlobData : UFO.Services.ViewAccess.DomainObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DataStreamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PathField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] DataStream {
            get {
                return this.DataStreamField;
            }
            set {
                if ((object.ReferenceEquals(this.DataStreamField, value) != true)) {
                    this.DataStreamField = value;
                    this.RaisePropertyChanged("DataStream");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path {
            get {
                return this.PathField;
            }
            set {
                if ((object.ReferenceEquals(this.PathField, value) != true)) {
                    this.PathField = value;
                    this.RaisePropertyChanged("Path");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Performance", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class Performance : UFO.Services.ViewAccess.DomainObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UFO.Services.ViewAccess.Artist ArtistField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UFO.Services.ViewAccess.Venue VenueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFO.Services.ViewAccess.Artist Artist {
            get {
                return this.ArtistField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtistField, value) != true)) {
                    this.ArtistField = value;
                    this.RaisePropertyChanged("Artist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime {
            get {
                return this.DateTimeField;
            }
            set {
                if ((this.DateTimeField.Equals(value) != true)) {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFO.Services.ViewAccess.Venue Venue {
            get {
                return this.VenueField;
            }
            set {
                if ((object.ReferenceEquals(this.VenueField, value) != true)) {
                    this.VenueField = value;
                    this.RaisePropertyChanged("Venue");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Venue", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class Venue : UFO.Services.ViewAccess.DomainObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UFO.Services.ViewAccess.Location LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VenueIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFO.Services.ViewAccess.Location Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VenueId {
            get {
                return this.VenueIdField;
            }
            set {
                if ((object.ReferenceEquals(this.VenueIdField, value) != true)) {
                    this.VenueIdField = value;
                    this.RaisePropertyChanged("VenueId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Location", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class Location : UFO.Services.ViewAccess.DomainObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LocationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LocationId {
            get {
                return this.LocationIdField;
            }
            set {
                if ((this.LocationIdField.Equals(value) != true)) {
                    this.LocationIdField = value;
                    this.RaisePropertyChanged("LocationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagingData", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class PagingData : UFO.Services.ViewAccess.DomainObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long OffsetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RemainingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SizeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Offset {
            get {
                return this.OffsetField;
            }
            set {
                if ((this.OffsetField.Equals(value) != true)) {
                    this.OffsetField = value;
                    this.RaisePropertyChanged("Offset");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Remaining {
            get {
                return this.RemainingField;
            }
            set {
                if ((this.RemainingField.Equals(value) != true)) {
                    this.RemainingField = value;
                    this.RaisePropertyChanged("Remaining");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Request {
            get {
                return this.RequestField;
            }
            set {
                if ((this.RequestField.Equals(value) != true)) {
                    this.RequestField = value;
                    this.RaisePropertyChanged("Request");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Size {
            get {
                return this.SizeField;
            }
            set {
                if ((this.SizeField.Equals(value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.ViewAccess.ViewAccessWs")]
    public interface ViewAccessWs {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/RequestArtistPagingData", ReplyAction="http://tempuri.org/ViewAccessWs/RequestArtistPagingDataResponse")]
        UFO.Services.ViewAccess.PagingData RequestArtistPagingData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/RequestArtistPagingData", ReplyAction="http://tempuri.org/ViewAccessWs/RequestArtistPagingDataResponse")]
        System.Threading.Tasks.Task<UFO.Services.ViewAccess.PagingData> RequestArtistPagingDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/RequestCategoryPagingData", ReplyAction="http://tempuri.org/ViewAccessWs/RequestCategoryPagingDataResponse")]
        UFO.Services.ViewAccess.PagingData RequestCategoryPagingData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/RequestCategoryPagingData", ReplyAction="http://tempuri.org/ViewAccessWs/RequestCategoryPagingDataResponse")]
        System.Threading.Tasks.Task<UFO.Services.ViewAccess.PagingData> RequestCategoryPagingDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/RequestCountryPagingData", ReplyAction="http://tempuri.org/ViewAccessWs/RequestCountryPagingDataResponse")]
        UFO.Services.ViewAccess.PagingData RequestCountryPagingData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/RequestCountryPagingData", ReplyAction="http://tempuri.org/ViewAccessWs/RequestCountryPagingDataResponse")]
        System.Threading.Tasks.Task<UFO.Services.ViewAccess.PagingData> RequestCountryPagingDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/RequestLocationPagingData", ReplyAction="http://tempuri.org/ViewAccessWs/RequestLocationPagingDataResponse")]
        UFO.Services.ViewAccess.PagingData RequestLocationPagingData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/RequestLocationPagingData", ReplyAction="http://tempuri.org/ViewAccessWs/RequestLocationPagingDataResponse")]
        System.Threading.Tasks.Task<UFO.Services.ViewAccess.PagingData> RequestLocationPagingDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/RequestPerformancePagingData", ReplyAction="http://tempuri.org/ViewAccessWs/RequestPerformancePagingDataResponse")]
        UFO.Services.ViewAccess.PagingData RequestPerformancePagingData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/RequestPerformancePagingData", ReplyAction="http://tempuri.org/ViewAccessWs/RequestPerformancePagingDataResponse")]
        System.Threading.Tasks.Task<UFO.Services.ViewAccess.PagingData> RequestPerformancePagingDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/RequestVenuePagingData", ReplyAction="http://tempuri.org/ViewAccessWs/RequestVenuePagingDataResponse")]
        UFO.Services.ViewAccess.PagingData RequestVenuePagingData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/RequestVenuePagingData", ReplyAction="http://tempuri.org/ViewAccessWs/RequestVenuePagingDataResponse")]
        System.Threading.Tasks.Task<UFO.Services.ViewAccess.PagingData> RequestVenuePagingDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetArtists", ReplyAction="http://tempuri.org/ViewAccessWs/GetArtistsResponse")]
        UFO.Services.ViewAccess.Artist[] GetArtists(UFO.Services.ViewAccess.PagingData page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetArtists", ReplyAction="http://tempuri.org/ViewAccessWs/GetArtistsResponse")]
        System.Threading.Tasks.Task<UFO.Services.ViewAccess.Artist[]> GetArtistsAsync(UFO.Services.ViewAccess.PagingData page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetArtist", ReplyAction="http://tempuri.org/ViewAccessWs/GetArtistResponse")]
        UFO.Services.ViewAccess.Artist GetArtist(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetArtist", ReplyAction="http://tempuri.org/ViewAccessWs/GetArtistResponse")]
        System.Threading.Tasks.Task<UFO.Services.ViewAccess.Artist> GetArtistAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetPerformances", ReplyAction="http://tempuri.org/ViewAccessWs/GetPerformancesResponse")]
        UFO.Services.ViewAccess.Performance[] GetPerformances(UFO.Services.ViewAccess.PagingData page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetPerformances", ReplyAction="http://tempuri.org/ViewAccessWs/GetPerformancesResponse")]
        System.Threading.Tasks.Task<UFO.Services.ViewAccess.Performance[]> GetPerformancesAsync(UFO.Services.ViewAccess.PagingData page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetPerformancesPerDate", ReplyAction="http://tempuri.org/ViewAccessWs/GetPerformancesPerDateResponse")]
        UFO.Services.ViewAccess.Performance[] GetPerformancesPerDate(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetPerformancesPerDate", ReplyAction="http://tempuri.org/ViewAccessWs/GetPerformancesPerDateResponse")]
        System.Threading.Tasks.Task<UFO.Services.ViewAccess.Performance[]> GetPerformancesPerDateAsync(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetPerformancesPerArtist", ReplyAction="http://tempuri.org/ViewAccessWs/GetPerformancesPerArtistResponse")]
        UFO.Services.ViewAccess.Performance[] GetPerformancesPerArtist(UFO.Services.ViewAccess.Artist artist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetPerformancesPerArtist", ReplyAction="http://tempuri.org/ViewAccessWs/GetPerformancesPerArtistResponse")]
        System.Threading.Tasks.Task<UFO.Services.ViewAccess.Performance[]> GetPerformancesPerArtistAsync(UFO.Services.ViewAccess.Artist artist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetPerformancesPerVenue", ReplyAction="http://tempuri.org/ViewAccessWs/GetPerformancesPerVenueResponse")]
        UFO.Services.ViewAccess.Performance[] GetPerformancesPerVenue(UFO.Services.ViewAccess.Venue venue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetPerformancesPerVenue", ReplyAction="http://tempuri.org/ViewAccessWs/GetPerformancesPerVenueResponse")]
        System.Threading.Tasks.Task<UFO.Services.ViewAccess.Performance[]> GetPerformancesPerVenueAsync(UFO.Services.ViewAccess.Venue venue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetLatestPerformances", ReplyAction="http://tempuri.org/ViewAccessWs/GetLatestPerformancesResponse")]
        UFO.Services.ViewAccess.Performance[] GetLatestPerformances();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetLatestPerformances", ReplyAction="http://tempuri.org/ViewAccessWs/GetLatestPerformancesResponse")]
        System.Threading.Tasks.Task<UFO.Services.ViewAccess.Performance[]> GetLatestPerformancesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetCategories", ReplyAction="http://tempuri.org/ViewAccessWs/GetCategoriesResponse")]
        UFO.Services.ViewAccess.Category[] GetCategories(UFO.Services.ViewAccess.PagingData page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetCategories", ReplyAction="http://tempuri.org/ViewAccessWs/GetCategoriesResponse")]
        System.Threading.Tasks.Task<UFO.Services.ViewAccess.Category[]> GetCategoriesAsync(UFO.Services.ViewAccess.PagingData page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetCountries", ReplyAction="http://tempuri.org/ViewAccessWs/GetCountriesResponse")]
        UFO.Services.ViewAccess.Country[] GetCountries(UFO.Services.ViewAccess.PagingData page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetCountries", ReplyAction="http://tempuri.org/ViewAccessWs/GetCountriesResponse")]
        System.Threading.Tasks.Task<UFO.Services.ViewAccess.Country[]> GetCountriesAsync(UFO.Services.ViewAccess.PagingData page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetLocations", ReplyAction="http://tempuri.org/ViewAccessWs/GetLocationsResponse")]
        UFO.Services.ViewAccess.Location[] GetLocations(UFO.Services.ViewAccess.PagingData page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetLocations", ReplyAction="http://tempuri.org/ViewAccessWs/GetLocationsResponse")]
        System.Threading.Tasks.Task<UFO.Services.ViewAccess.Location[]> GetLocationsAsync(UFO.Services.ViewAccess.PagingData page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetVenues", ReplyAction="http://tempuri.org/ViewAccessWs/GetVenuesResponse")]
        UFO.Services.ViewAccess.Venue[] GetVenues(UFO.Services.ViewAccess.PagingData page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetVenues", ReplyAction="http://tempuri.org/ViewAccessWs/GetVenuesResponse")]
        System.Threading.Tasks.Task<UFO.Services.ViewAccess.Venue[]> GetVenuesAsync(UFO.Services.ViewAccess.PagingData page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetVenue", ReplyAction="http://tempuri.org/ViewAccessWs/GetVenueResponse")]
        UFO.Services.ViewAccess.Venue GetVenue(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetVenue", ReplyAction="http://tempuri.org/ViewAccessWs/GetVenueResponse")]
        System.Threading.Tasks.Task<UFO.Services.ViewAccess.Venue> GetVenueAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/SearchPerformancesPerKeyword", ReplyAction="http://tempuri.org/ViewAccessWs/SearchPerformancesPerKeywordResponse")]
        UFO.Services.ViewAccess.Performance[] SearchPerformancesPerKeyword(string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/SearchPerformancesPerKeyword", ReplyAction="http://tempuri.org/ViewAccessWs/SearchPerformancesPerKeywordResponse")]
        System.Threading.Tasks.Task<UFO.Services.ViewAccess.Performance[]> SearchPerformancesPerKeywordAsync(string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/SearchVenuesPerKeyword", ReplyAction="http://tempuri.org/ViewAccessWs/SearchVenuesPerKeywordResponse")]
        UFO.Services.ViewAccess.Venue[] SearchVenuesPerKeyword(string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/SearchVenuesPerKeyword", ReplyAction="http://tempuri.org/ViewAccessWs/SearchVenuesPerKeywordResponse")]
        System.Threading.Tasks.Task<UFO.Services.ViewAccess.Venue[]> SearchVenuesPerKeywordAsync(string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/SearchArtistsPerKeyword", ReplyAction="http://tempuri.org/ViewAccessWs/SearchArtistsPerKeywordResponse")]
        UFO.Services.ViewAccess.Artist[] SearchArtistsPerKeyword(string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/SearchArtistsPerKeyword", ReplyAction="http://tempuri.org/ViewAccessWs/SearchArtistsPerKeywordResponse")]
        System.Threading.Tasks.Task<UFO.Services.ViewAccess.Artist[]> SearchArtistsPerKeywordAsync(string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetPerformanceAutoCompletion", ReplyAction="http://tempuri.org/ViewAccessWs/GetPerformanceAutoCompletionResponse")]
        string[] GetPerformanceAutoCompletion(string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetPerformanceAutoCompletion", ReplyAction="http://tempuri.org/ViewAccessWs/GetPerformanceAutoCompletionResponse")]
        System.Threading.Tasks.Task<string[]> GetPerformanceAutoCompletionAsync(string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetAllPerformanceDates", ReplyAction="http://tempuri.org/ViewAccessWs/GetAllPerformanceDatesResponse")]
        System.DateTime[] GetAllPerformanceDates();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetAllPerformanceDates", ReplyAction="http://tempuri.org/ViewAccessWs/GetAllPerformanceDatesResponse")]
        System.Threading.Tasks.Task<System.DateTime[]> GetAllPerformanceDatesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ViewAccessWsChannel : UFO.Services.ViewAccess.ViewAccessWs, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ViewAccessWsClient : System.ServiceModel.ClientBase<UFO.Services.ViewAccess.ViewAccessWs>, UFO.Services.ViewAccess.ViewAccessWs {
        
        public ViewAccessWsClient() {
        }
        
        public ViewAccessWsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ViewAccessWsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ViewAccessWsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ViewAccessWsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UFO.Services.ViewAccess.PagingData RequestArtistPagingData() {
            return base.Channel.RequestArtistPagingData();
        }
        
        public System.Threading.Tasks.Task<UFO.Services.ViewAccess.PagingData> RequestArtistPagingDataAsync() {
            return base.Channel.RequestArtistPagingDataAsync();
        }
        
        public UFO.Services.ViewAccess.PagingData RequestCategoryPagingData() {
            return base.Channel.RequestCategoryPagingData();
        }
        
        public System.Threading.Tasks.Task<UFO.Services.ViewAccess.PagingData> RequestCategoryPagingDataAsync() {
            return base.Channel.RequestCategoryPagingDataAsync();
        }
        
        public UFO.Services.ViewAccess.PagingData RequestCountryPagingData() {
            return base.Channel.RequestCountryPagingData();
        }
        
        public System.Threading.Tasks.Task<UFO.Services.ViewAccess.PagingData> RequestCountryPagingDataAsync() {
            return base.Channel.RequestCountryPagingDataAsync();
        }
        
        public UFO.Services.ViewAccess.PagingData RequestLocationPagingData() {
            return base.Channel.RequestLocationPagingData();
        }
        
        public System.Threading.Tasks.Task<UFO.Services.ViewAccess.PagingData> RequestLocationPagingDataAsync() {
            return base.Channel.RequestLocationPagingDataAsync();
        }
        
        public UFO.Services.ViewAccess.PagingData RequestPerformancePagingData() {
            return base.Channel.RequestPerformancePagingData();
        }
        
        public System.Threading.Tasks.Task<UFO.Services.ViewAccess.PagingData> RequestPerformancePagingDataAsync() {
            return base.Channel.RequestPerformancePagingDataAsync();
        }
        
        public UFO.Services.ViewAccess.PagingData RequestVenuePagingData() {
            return base.Channel.RequestVenuePagingData();
        }
        
        public System.Threading.Tasks.Task<UFO.Services.ViewAccess.PagingData> RequestVenuePagingDataAsync() {
            return base.Channel.RequestVenuePagingDataAsync();
        }
        
        public UFO.Services.ViewAccess.Artist[] GetArtists(UFO.Services.ViewAccess.PagingData page) {
            return base.Channel.GetArtists(page);
        }
        
        public System.Threading.Tasks.Task<UFO.Services.ViewAccess.Artist[]> GetArtistsAsync(UFO.Services.ViewAccess.PagingData page) {
            return base.Channel.GetArtistsAsync(page);
        }
        
        public UFO.Services.ViewAccess.Artist GetArtist(int id) {
            return base.Channel.GetArtist(id);
        }
        
        public System.Threading.Tasks.Task<UFO.Services.ViewAccess.Artist> GetArtistAsync(int id) {
            return base.Channel.GetArtistAsync(id);
        }
        
        public UFO.Services.ViewAccess.Performance[] GetPerformances(UFO.Services.ViewAccess.PagingData page) {
            return base.Channel.GetPerformances(page);
        }
        
        public System.Threading.Tasks.Task<UFO.Services.ViewAccess.Performance[]> GetPerformancesAsync(UFO.Services.ViewAccess.PagingData page) {
            return base.Channel.GetPerformancesAsync(page);
        }
        
        public UFO.Services.ViewAccess.Performance[] GetPerformancesPerDate(System.DateTime date) {
            return base.Channel.GetPerformancesPerDate(date);
        }
        
        public System.Threading.Tasks.Task<UFO.Services.ViewAccess.Performance[]> GetPerformancesPerDateAsync(System.DateTime date) {
            return base.Channel.GetPerformancesPerDateAsync(date);
        }
        
        public UFO.Services.ViewAccess.Performance[] GetPerformancesPerArtist(UFO.Services.ViewAccess.Artist artist) {
            return base.Channel.GetPerformancesPerArtist(artist);
        }
        
        public System.Threading.Tasks.Task<UFO.Services.ViewAccess.Performance[]> GetPerformancesPerArtistAsync(UFO.Services.ViewAccess.Artist artist) {
            return base.Channel.GetPerformancesPerArtistAsync(artist);
        }
        
        public UFO.Services.ViewAccess.Performance[] GetPerformancesPerVenue(UFO.Services.ViewAccess.Venue venue) {
            return base.Channel.GetPerformancesPerVenue(venue);
        }
        
        public System.Threading.Tasks.Task<UFO.Services.ViewAccess.Performance[]> GetPerformancesPerVenueAsync(UFO.Services.ViewAccess.Venue venue) {
            return base.Channel.GetPerformancesPerVenueAsync(venue);
        }
        
        public UFO.Services.ViewAccess.Performance[] GetLatestPerformances() {
            return base.Channel.GetLatestPerformances();
        }
        
        public System.Threading.Tasks.Task<UFO.Services.ViewAccess.Performance[]> GetLatestPerformancesAsync() {
            return base.Channel.GetLatestPerformancesAsync();
        }
        
        public UFO.Services.ViewAccess.Category[] GetCategories(UFO.Services.ViewAccess.PagingData page) {
            return base.Channel.GetCategories(page);
        }
        
        public System.Threading.Tasks.Task<UFO.Services.ViewAccess.Category[]> GetCategoriesAsync(UFO.Services.ViewAccess.PagingData page) {
            return base.Channel.GetCategoriesAsync(page);
        }
        
        public UFO.Services.ViewAccess.Country[] GetCountries(UFO.Services.ViewAccess.PagingData page) {
            return base.Channel.GetCountries(page);
        }
        
        public System.Threading.Tasks.Task<UFO.Services.ViewAccess.Country[]> GetCountriesAsync(UFO.Services.ViewAccess.PagingData page) {
            return base.Channel.GetCountriesAsync(page);
        }
        
        public UFO.Services.ViewAccess.Location[] GetLocations(UFO.Services.ViewAccess.PagingData page) {
            return base.Channel.GetLocations(page);
        }
        
        public System.Threading.Tasks.Task<UFO.Services.ViewAccess.Location[]> GetLocationsAsync(UFO.Services.ViewAccess.PagingData page) {
            return base.Channel.GetLocationsAsync(page);
        }
        
        public UFO.Services.ViewAccess.Venue[] GetVenues(UFO.Services.ViewAccess.PagingData page) {
            return base.Channel.GetVenues(page);
        }
        
        public System.Threading.Tasks.Task<UFO.Services.ViewAccess.Venue[]> GetVenuesAsync(UFO.Services.ViewAccess.PagingData page) {
            return base.Channel.GetVenuesAsync(page);
        }
        
        public UFO.Services.ViewAccess.Venue GetVenue(string id) {
            return base.Channel.GetVenue(id);
        }
        
        public System.Threading.Tasks.Task<UFO.Services.ViewAccess.Venue> GetVenueAsync(string id) {
            return base.Channel.GetVenueAsync(id);
        }
        
        public UFO.Services.ViewAccess.Performance[] SearchPerformancesPerKeyword(string keyword) {
            return base.Channel.SearchPerformancesPerKeyword(keyword);
        }
        
        public System.Threading.Tasks.Task<UFO.Services.ViewAccess.Performance[]> SearchPerformancesPerKeywordAsync(string keyword) {
            return base.Channel.SearchPerformancesPerKeywordAsync(keyword);
        }
        
        public UFO.Services.ViewAccess.Venue[] SearchVenuesPerKeyword(string keyword) {
            return base.Channel.SearchVenuesPerKeyword(keyword);
        }
        
        public System.Threading.Tasks.Task<UFO.Services.ViewAccess.Venue[]> SearchVenuesPerKeywordAsync(string keyword) {
            return base.Channel.SearchVenuesPerKeywordAsync(keyword);
        }
        
        public UFO.Services.ViewAccess.Artist[] SearchArtistsPerKeyword(string keyword) {
            return base.Channel.SearchArtistsPerKeyword(keyword);
        }
        
        public System.Threading.Tasks.Task<UFO.Services.ViewAccess.Artist[]> SearchArtistsPerKeywordAsync(string keyword) {
            return base.Channel.SearchArtistsPerKeywordAsync(keyword);
        }
        
        public string[] GetPerformanceAutoCompletion(string keyword) {
            return base.Channel.GetPerformanceAutoCompletion(keyword);
        }
        
        public System.Threading.Tasks.Task<string[]> GetPerformanceAutoCompletionAsync(string keyword) {
            return base.Channel.GetPerformanceAutoCompletionAsync(keyword);
        }
        
        public System.DateTime[] GetAllPerformanceDates() {
            return base.Channel.GetAllPerformanceDates();
        }
        
        public System.Threading.Tasks.Task<System.DateTime[]> GetAllPerformanceDatesAsync() {
            return base.Channel.GetAllPerformanceDatesAsync();
        }
    }
}
