//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UFO.Services.ViewAccess {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DomainObject", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFO.Services.ViewAccess.Category))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFO.Services.ViewAccess.Country))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFO.Services.ViewAccess.BlobData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFO.Services.ViewAccess.SessionToken))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFO.Services.ViewAccess.User))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFO.Services.ViewAccess.Location))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFO.Services.ViewAccess.Venue))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UFO.Services.ViewAccess.Artist))]
    public partial class DomainObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class Category : UFO.Services.ViewAccess.DomainObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryIdField, value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Country", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class Country : UFO.Services.ViewAccess.DomainObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BlobData", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class BlobData : UFO.Services.ViewAccess.DomainObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DataStreamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PathField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] DataStream {
            get {
                return this.DataStreamField;
            }
            set {
                if ((object.ReferenceEquals(this.DataStreamField, value) != true)) {
                    this.DataStreamField = value;
                    this.RaisePropertyChanged("DataStream");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path {
            get {
                return this.PathField;
            }
            set {
                if ((object.ReferenceEquals(this.PathField, value) != true)) {
                    this.PathField = value;
                    this.RaisePropertyChanged("Path");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SessionToken", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class SessionToken : UFO.Services.ViewAccess.DomainObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char[] SessionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UFO.Services.ViewAccess.User UserField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char[] SessionId {
            get {
                return this.SessionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionIdField, value) != true)) {
                    this.SessionIdField = value;
                    this.RaisePropertyChanged("SessionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFO.Services.ViewAccess.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class User : UFO.Services.ViewAccess.DomainObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UFO.Services.ViewAccess.Artist ArtistField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsArtistField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFO.Services.ViewAccess.Artist Artist {
            get {
                return this.ArtistField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtistField, value) != true)) {
                    this.ArtistField = value;
                    this.RaisePropertyChanged("Artist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMail {
            get {
                return this.EMailField;
            }
            set {
                if ((object.ReferenceEquals(this.EMailField, value) != true)) {
                    this.EMailField = value;
                    this.RaisePropertyChanged("EMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAdmin {
            get {
                return this.IsAdminField;
            }
            set {
                if ((this.IsAdminField.Equals(value) != true)) {
                    this.IsAdminField = value;
                    this.RaisePropertyChanged("IsAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsArtist {
            get {
                return this.IsArtistField;
            }
            set {
                if ((this.IsArtistField.Equals(value) != true)) {
                    this.IsArtistField = value;
                    this.RaisePropertyChanged("IsArtist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Location", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class Location : UFO.Services.ViewAccess.DomainObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LocationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LocationId {
            get {
                return this.LocationIdField;
            }
            set {
                if ((this.LocationIdField.Equals(value) != true)) {
                    this.LocationIdField = value;
                    this.RaisePropertyChanged("LocationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Venue", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class Venue : UFO.Services.ViewAccess.DomainObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UFO.Services.ViewAccess.Location LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VenueIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFO.Services.ViewAccess.Location Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VenueId {
            get {
                return this.VenueIdField;
            }
            set {
                if ((object.ReferenceEquals(this.VenueIdField, value) != true)) {
                    this.VenueIdField = value;
                    this.RaisePropertyChanged("VenueId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Artist", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class Artist : UFO.Services.ViewAccess.DomainObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ArtistIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UFO.Services.ViewAccess.Category CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UFO.Services.ViewAccess.Country CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UFO.Services.ViewAccess.BlobData PictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PromoVideoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ArtistId {
            get {
                return this.ArtistIdField;
            }
            set {
                if ((this.ArtistIdField.Equals(value) != true)) {
                    this.ArtistIdField = value;
                    this.RaisePropertyChanged("ArtistId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFO.Services.ViewAccess.Category Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFO.Services.ViewAccess.Country Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMail {
            get {
                return this.EMailField;
            }
            set {
                if ((object.ReferenceEquals(this.EMailField, value) != true)) {
                    this.EMailField = value;
                    this.RaisePropertyChanged("EMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UFO.Services.ViewAccess.BlobData Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PromoVideo {
            get {
                return this.PromoVideoField;
            }
            set {
                if ((object.ReferenceEquals(this.PromoVideoField, value) != true)) {
                    this.PromoVideoField = value;
                    this.RaisePropertyChanged("PromoVideo");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.ViewAccess.AdminAccessWs")]
    public interface AdminAccessWs {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/InsertArtist", ReplyAction="http://tempuri.org/AdminAccessWs/InsertArtistResponse")]
        void InsertArtist(UFO.Services.ViewAccess.Artist artist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/InsertArtist", ReplyAction="http://tempuri.org/AdminAccessWs/InsertArtistResponse")]
        System.Threading.Tasks.Task InsertArtistAsync(UFO.Services.ViewAccess.Artist artist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/GetAll", ReplyAction="http://tempuri.org/AdminAccessWs/GetAllResponse")]
        UFO.Services.ViewAccess.User[] GetAll(UFO.Services.ViewAccess.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/GetAll", ReplyAction="http://tempuri.org/AdminAccessWs/GetAllResponse")]
        System.Threading.Tasks.Task<UFO.Services.ViewAccess.User[]> GetAllAsync(UFO.Services.ViewAccess.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/IsUserAuthenticated", ReplyAction="http://tempuri.org/AdminAccessWs/IsUserAuthenticatedResponse")]
        bool IsUserAuthenticated(UFO.Services.ViewAccess.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/IsUserAuthenticated", ReplyAction="http://tempuri.org/AdminAccessWs/IsUserAuthenticatedResponse")]
        System.Threading.Tasks.Task<bool> IsUserAuthenticatedAsync(UFO.Services.ViewAccess.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/IsValidAdmin", ReplyAction="http://tempuri.org/AdminAccessWs/IsValidAdminResponse")]
        bool IsValidAdmin(UFO.Services.ViewAccess.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/IsValidAdmin", ReplyAction="http://tempuri.org/AdminAccessWs/IsValidAdminResponse")]
        System.Threading.Tasks.Task<bool> IsValidAdminAsync(UFO.Services.ViewAccess.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/LoginAdmin", ReplyAction="http://tempuri.org/AdminAccessWs/LoginAdminResponse")]
        bool LoginAdmin(UFO.Services.ViewAccess.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/LoginAdmin", ReplyAction="http://tempuri.org/AdminAccessWs/LoginAdminResponse")]
        System.Threading.Tasks.Task<bool> LoginAdminAsync(UFO.Services.ViewAccess.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/LogoutAdmin", ReplyAction="http://tempuri.org/AdminAccessWs/LogoutAdminResponse")]
        void LogoutAdmin(UFO.Services.ViewAccess.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/LogoutAdmin", ReplyAction="http://tempuri.org/AdminAccessWs/LogoutAdminResponse")]
        System.Threading.Tasks.Task LogoutAdminAsync(UFO.Services.ViewAccess.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/RequestSessionToken", ReplyAction="http://tempuri.org/AdminAccessWs/RequestSessionTokenResponse")]
        UFO.Services.ViewAccess.SessionToken RequestSessionToken(UFO.Services.ViewAccess.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdminAccessWs/RequestSessionToken", ReplyAction="http://tempuri.org/AdminAccessWs/RequestSessionTokenResponse")]
        System.Threading.Tasks.Task<UFO.Services.ViewAccess.SessionToken> RequestSessionTokenAsync(UFO.Services.ViewAccess.User user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AdminAccessWsChannel : UFO.Services.ViewAccess.AdminAccessWs, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminAccessWsClient : System.ServiceModel.ClientBase<UFO.Services.ViewAccess.AdminAccessWs>, UFO.Services.ViewAccess.AdminAccessWs {
        
        public AdminAccessWsClient() {
        }
        
        public AdminAccessWsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminAccessWsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminAccessWsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminAccessWsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsertArtist(UFO.Services.ViewAccess.Artist artist) {
            base.Channel.InsertArtist(artist);
        }
        
        public System.Threading.Tasks.Task InsertArtistAsync(UFO.Services.ViewAccess.Artist artist) {
            return base.Channel.InsertArtistAsync(artist);
        }
        
        public UFO.Services.ViewAccess.User[] GetAll(UFO.Services.ViewAccess.SessionToken token) {
            return base.Channel.GetAll(token);
        }
        
        public System.Threading.Tasks.Task<UFO.Services.ViewAccess.User[]> GetAllAsync(UFO.Services.ViewAccess.SessionToken token) {
            return base.Channel.GetAllAsync(token);
        }
        
        public bool IsUserAuthenticated(UFO.Services.ViewAccess.SessionToken token) {
            return base.Channel.IsUserAuthenticated(token);
        }
        
        public System.Threading.Tasks.Task<bool> IsUserAuthenticatedAsync(UFO.Services.ViewAccess.SessionToken token) {
            return base.Channel.IsUserAuthenticatedAsync(token);
        }
        
        public bool IsValidAdmin(UFO.Services.ViewAccess.SessionToken token) {
            return base.Channel.IsValidAdmin(token);
        }
        
        public System.Threading.Tasks.Task<bool> IsValidAdminAsync(UFO.Services.ViewAccess.SessionToken token) {
            return base.Channel.IsValidAdminAsync(token);
        }
        
        public bool LoginAdmin(UFO.Services.ViewAccess.SessionToken token) {
            return base.Channel.LoginAdmin(token);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAdminAsync(UFO.Services.ViewAccess.SessionToken token) {
            return base.Channel.LoginAdminAsync(token);
        }
        
        public void LogoutAdmin(UFO.Services.ViewAccess.SessionToken token) {
            base.Channel.LogoutAdmin(token);
        }
        
        public System.Threading.Tasks.Task LogoutAdminAsync(UFO.Services.ViewAccess.SessionToken token) {
            return base.Channel.LogoutAdminAsync(token);
        }
        
        public UFO.Services.ViewAccess.SessionToken RequestSessionToken(UFO.Services.ViewAccess.User user) {
            return base.Channel.RequestSessionToken(user);
        }
        
        public System.Threading.Tasks.Task<UFO.Services.ViewAccess.SessionToken> RequestSessionTokenAsync(UFO.Services.ViewAccess.User user) {
            return base.Channel.RequestSessionTokenAsync(user);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.ViewAccess.ViewAccessWs")]
    public interface ViewAccessWs {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetAllArtist", ReplyAction="http://tempuri.org/ViewAccessWs/GetAllArtistResponse")]
        UFO.Services.ViewAccess.Artist[] GetAllArtist();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetAllArtist", ReplyAction="http://tempuri.org/ViewAccessWs/GetAllArtistResponse")]
        System.Threading.Tasks.Task<UFO.Services.ViewAccess.Artist[]> GetAllArtistAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetArtistWhereCatrgory", ReplyAction="http://tempuri.org/ViewAccessWs/GetArtistWhereCatrgoryResponse")]
        UFO.Services.ViewAccess.Artist[] GetArtistWhereCatrgory(UFO.Services.ViewAccess.Category category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetArtistWhereCatrgory", ReplyAction="http://tempuri.org/ViewAccessWs/GetArtistWhereCatrgoryResponse")]
        System.Threading.Tasks.Task<UFO.Services.ViewAccess.Artist[]> GetArtistWhereCatrgoryAsync(UFO.Services.ViewAccess.Category category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetAllCategories", ReplyAction="http://tempuri.org/ViewAccessWs/GetAllCategoriesResponse")]
        UFO.Services.ViewAccess.Category[] GetAllCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetAllCategories", ReplyAction="http://tempuri.org/ViewAccessWs/GetAllCategoriesResponse")]
        System.Threading.Tasks.Task<UFO.Services.ViewAccess.Category[]> GetAllCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetAllCountries", ReplyAction="http://tempuri.org/ViewAccessWs/GetAllCountriesResponse")]
        UFO.Services.ViewAccess.Country[] GetAllCountries();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetAllCountries", ReplyAction="http://tempuri.org/ViewAccessWs/GetAllCountriesResponse")]
        System.Threading.Tasks.Task<UFO.Services.ViewAccess.Country[]> GetAllCountriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetAllLocations", ReplyAction="http://tempuri.org/ViewAccessWs/GetAllLocationsResponse")]
        UFO.Services.ViewAccess.Location[] GetAllLocations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetAllLocations", ReplyAction="http://tempuri.org/ViewAccessWs/GetAllLocationsResponse")]
        System.Threading.Tasks.Task<UFO.Services.ViewAccess.Location[]> GetAllLocationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetAllVenues", ReplyAction="http://tempuri.org/ViewAccessWs/GetAllVenuesResponse")]
        UFO.Services.ViewAccess.Venue[] GetAllVenues();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAccessWs/GetAllVenues", ReplyAction="http://tempuri.org/ViewAccessWs/GetAllVenuesResponse")]
        System.Threading.Tasks.Task<UFO.Services.ViewAccess.Venue[]> GetAllVenuesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ViewAccessWsChannel : UFO.Services.ViewAccess.ViewAccessWs, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ViewAccessWsClient : System.ServiceModel.ClientBase<UFO.Services.ViewAccess.ViewAccessWs>, UFO.Services.ViewAccess.ViewAccessWs {
        
        public ViewAccessWsClient() {
        }
        
        public ViewAccessWsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ViewAccessWsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ViewAccessWsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ViewAccessWsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UFO.Services.ViewAccess.Artist[] GetAllArtist() {
            return base.Channel.GetAllArtist();
        }
        
        public System.Threading.Tasks.Task<UFO.Services.ViewAccess.Artist[]> GetAllArtistAsync() {
            return base.Channel.GetAllArtistAsync();
        }
        
        public UFO.Services.ViewAccess.Artist[] GetArtistWhereCatrgory(UFO.Services.ViewAccess.Category category) {
            return base.Channel.GetArtistWhereCatrgory(category);
        }
        
        public System.Threading.Tasks.Task<UFO.Services.ViewAccess.Artist[]> GetArtistWhereCatrgoryAsync(UFO.Services.ViewAccess.Category category) {
            return base.Channel.GetArtistWhereCatrgoryAsync(category);
        }
        
        public UFO.Services.ViewAccess.Category[] GetAllCategories() {
            return base.Channel.GetAllCategories();
        }
        
        public System.Threading.Tasks.Task<UFO.Services.ViewAccess.Category[]> GetAllCategoriesAsync() {
            return base.Channel.GetAllCategoriesAsync();
        }
        
        public UFO.Services.ViewAccess.Country[] GetAllCountries() {
            return base.Channel.GetAllCountries();
        }
        
        public System.Threading.Tasks.Task<UFO.Services.ViewAccess.Country[]> GetAllCountriesAsync() {
            return base.Channel.GetAllCountriesAsync();
        }
        
        public UFO.Services.ViewAccess.Location[] GetAllLocations() {
            return base.Channel.GetAllLocations();
        }
        
        public System.Threading.Tasks.Task<UFO.Services.ViewAccess.Location[]> GetAllLocationsAsync() {
            return base.Channel.GetAllLocationsAsync();
        }
        
        public UFO.Services.ViewAccess.Venue[] GetAllVenues() {
            return base.Channel.GetAllVenues();
        }
        
        public System.Threading.Tasks.Task<UFO.Services.ViewAccess.Venue[]> GetAllVenuesAsync() {
            return base.Channel.GetAllVenuesAsync();
        }
    }
}
