//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UFO.Server {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SessionToken", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Bll.Common")]
    [System.SerializableAttribute()]
    public partial class SessionToken : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private char[] SessionIdk__BackingFieldField;
        
        private UFO.Server.User Userk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<SessionId>k__BackingField", IsRequired=true)]
        public char[] SessionIdk__BackingField {
            get {
                return this.SessionIdk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionIdk__BackingFieldField, value) != true)) {
                    this.SessionIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("SessionIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<User>k__BackingField", IsRequired=true)]
        public UFO.Server.User Userk__BackingField {
            get {
                return this.Userk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Userk__BackingFieldField, value) != true)) {
                    this.Userk__BackingFieldField = value;
                    this.RaisePropertyChanged("Userk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private UFO.Server.Artist Artistk__BackingFieldField;
        
        private string EMailk__BackingFieldField;
        
        private string FirstNamek__BackingFieldField;
        
        private bool IsAdmink__BackingFieldField;
        
        private bool IsArtistk__BackingFieldField;
        
        private string LastNamek__BackingFieldField;
        
        private string Passwordk__BackingFieldField;
        
        private int UserIdk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Artist>k__BackingField", IsRequired=true)]
        public UFO.Server.Artist Artistk__BackingField {
            get {
                return this.Artistk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Artistk__BackingFieldField, value) != true)) {
                    this.Artistk__BackingFieldField = value;
                    this.RaisePropertyChanged("Artistk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<EMail>k__BackingField", IsRequired=true)]
        public string EMailk__BackingField {
            get {
                return this.EMailk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.EMailk__BackingFieldField, value) != true)) {
                    this.EMailk__BackingFieldField = value;
                    this.RaisePropertyChanged("EMailk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<FirstName>k__BackingField", IsRequired=true)]
        public string FirstNamek__BackingField {
            get {
                return this.FirstNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNamek__BackingFieldField, value) != true)) {
                    this.FirstNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("FirstNamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<IsAdmin>k__BackingField", IsRequired=true)]
        public bool IsAdmink__BackingField {
            get {
                return this.IsAdmink__BackingFieldField;
            }
            set {
                if ((this.IsAdmink__BackingFieldField.Equals(value) != true)) {
                    this.IsAdmink__BackingFieldField = value;
                    this.RaisePropertyChanged("IsAdmink__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<IsArtist>k__BackingField", IsRequired=true)]
        public bool IsArtistk__BackingField {
            get {
                return this.IsArtistk__BackingFieldField;
            }
            set {
                if ((this.IsArtistk__BackingFieldField.Equals(value) != true)) {
                    this.IsArtistk__BackingFieldField = value;
                    this.RaisePropertyChanged("IsArtistk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<LastName>k__BackingField", IsRequired=true)]
        public string LastNamek__BackingField {
            get {
                return this.LastNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNamek__BackingFieldField, value) != true)) {
                    this.LastNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("LastNamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Password>k__BackingField", IsRequired=true)]
        public string Passwordk__BackingField {
            get {
                return this.Passwordk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Passwordk__BackingFieldField, value) != true)) {
                    this.Passwordk__BackingFieldField = value;
                    this.RaisePropertyChanged("Passwordk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<UserId>k__BackingField", IsRequired=true)]
        public int UserIdk__BackingField {
            get {
                return this.UserIdk__BackingFieldField;
            }
            set {
                if ((this.UserIdk__BackingFieldField.Equals(value) != true)) {
                    this.UserIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("UserIdk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Artist", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class Artist : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ArtistIdk__BackingFieldField;
        
        private UFO.Server.Category Categoryk__BackingFieldField;
        
        private UFO.Server.Country Countryk__BackingFieldField;
        
        private string EMailk__BackingFieldField;
        
        private string Namek__BackingFieldField;
        
        private UFO.Server.BlobData Picturek__BackingFieldField;
        
        private string PromoVideok__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ArtistId>k__BackingField", IsRequired=true)]
        public int ArtistIdk__BackingField {
            get {
                return this.ArtistIdk__BackingFieldField;
            }
            set {
                if ((this.ArtistIdk__BackingFieldField.Equals(value) != true)) {
                    this.ArtistIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("ArtistIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Category>k__BackingField", IsRequired=true)]
        public UFO.Server.Category Categoryk__BackingField {
            get {
                return this.Categoryk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Categoryk__BackingFieldField, value) != true)) {
                    this.Categoryk__BackingFieldField = value;
                    this.RaisePropertyChanged("Categoryk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Country>k__BackingField", IsRequired=true)]
        public UFO.Server.Country Countryk__BackingField {
            get {
                return this.Countryk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Countryk__BackingFieldField, value) != true)) {
                    this.Countryk__BackingFieldField = value;
                    this.RaisePropertyChanged("Countryk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<EMail>k__BackingField", IsRequired=true)]
        public string EMailk__BackingField {
            get {
                return this.EMailk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.EMailk__BackingFieldField, value) != true)) {
                    this.EMailk__BackingFieldField = value;
                    this.RaisePropertyChanged("EMailk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Name>k__BackingField", IsRequired=true)]
        public string Namek__BackingField {
            get {
                return this.Namek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Namek__BackingFieldField, value) != true)) {
                    this.Namek__BackingFieldField = value;
                    this.RaisePropertyChanged("Namek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Picture>k__BackingField", IsRequired=true)]
        public UFO.Server.BlobData Picturek__BackingField {
            get {
                return this.Picturek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Picturek__BackingFieldField, value) != true)) {
                    this.Picturek__BackingFieldField = value;
                    this.RaisePropertyChanged("Picturek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<PromoVideo>k__BackingField", IsRequired=true)]
        public string PromoVideok__BackingField {
            get {
                return this.PromoVideok__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.PromoVideok__BackingFieldField, value) != true)) {
                    this.PromoVideok__BackingFieldField = value;
                    this.RaisePropertyChanged("PromoVideok__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CategoryIdk__BackingFieldField;
        
        private string Namek__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CategoryId>k__BackingField", IsRequired=true)]
        public string CategoryIdk__BackingField {
            get {
                return this.CategoryIdk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryIdk__BackingFieldField, value) != true)) {
                    this.CategoryIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("CategoryIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Name>k__BackingField", IsRequired=true)]
        public string Namek__BackingField {
            get {
                return this.Namek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Namek__BackingFieldField, value) != true)) {
                    this.Namek__BackingFieldField = value;
                    this.RaisePropertyChanged("Namek__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Country", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class Country : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string Codek__BackingFieldField;
        
        private string Namek__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Code>k__BackingField", IsRequired=true)]
        public string Codek__BackingField {
            get {
                return this.Codek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Codek__BackingFieldField, value) != true)) {
                    this.Codek__BackingFieldField = value;
                    this.RaisePropertyChanged("Codek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Name>k__BackingField", IsRequired=true)]
        public string Namek__BackingField {
            get {
                return this.Namek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Namek__BackingFieldField, value) != true)) {
                    this.Namek__BackingFieldField = value;
                    this.RaisePropertyChanged("Namek__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BlobData", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class BlobData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private byte[] DataStreamk__BackingFieldField;
        
        private string Namek__BackingFieldField;
        
        private string Pathk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DataStream>k__BackingField", IsRequired=true)]
        public byte[] DataStreamk__BackingField {
            get {
                return this.DataStreamk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.DataStreamk__BackingFieldField, value) != true)) {
                    this.DataStreamk__BackingFieldField = value;
                    this.RaisePropertyChanged("DataStreamk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Name>k__BackingField", IsRequired=true)]
        public string Namek__BackingField {
            get {
                return this.Namek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Namek__BackingFieldField, value) != true)) {
                    this.Namek__BackingFieldField = value;
                    this.RaisePropertyChanged("Namek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Path>k__BackingField", IsRequired=true)]
        public string Pathk__BackingField {
            get {
                return this.Pathk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Pathk__BackingFieldField, value) != true)) {
                    this.Pathk__BackingFieldField = value;
                    this.RaisePropertyChanged("Pathk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Server.IAuthAccessBll")]
    public interface IAuthAccessBll {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthAccessBll/GetAll", ReplyAction="http://tempuri.org/IAuthAccessBll/GetAllResponse")]
        UFO.Server.User[] GetAll(UFO.Server.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthAccessBll/GetAll", ReplyAction="http://tempuri.org/IAuthAccessBll/GetAllResponse")]
        System.Threading.Tasks.Task<UFO.Server.User[]> GetAllAsync(UFO.Server.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthAccessBll/IsUserAuthenticated", ReplyAction="http://tempuri.org/IAuthAccessBll/IsUserAuthenticatedResponse")]
        bool IsUserAuthenticated(UFO.Server.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthAccessBll/IsUserAuthenticated", ReplyAction="http://tempuri.org/IAuthAccessBll/IsUserAuthenticatedResponse")]
        System.Threading.Tasks.Task<bool> IsUserAuthenticatedAsync(UFO.Server.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthAccessBll/IsValidAdmin", ReplyAction="http://tempuri.org/IAuthAccessBll/IsValidAdminResponse")]
        bool IsValidAdmin(UFO.Server.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthAccessBll/IsValidAdmin", ReplyAction="http://tempuri.org/IAuthAccessBll/IsValidAdminResponse")]
        System.Threading.Tasks.Task<bool> IsValidAdminAsync(UFO.Server.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthAccessBll/LoginAdmin", ReplyAction="http://tempuri.org/IAuthAccessBll/LoginAdminResponse")]
        bool LoginAdmin(UFO.Server.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthAccessBll/LoginAdmin", ReplyAction="http://tempuri.org/IAuthAccessBll/LoginAdminResponse")]
        System.Threading.Tasks.Task<bool> LoginAdminAsync(UFO.Server.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthAccessBll/LogoutAdmin", ReplyAction="http://tempuri.org/IAuthAccessBll/LogoutAdminResponse")]
        void LogoutAdmin(UFO.Server.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthAccessBll/LogoutAdmin", ReplyAction="http://tempuri.org/IAuthAccessBll/LogoutAdminResponse")]
        System.Threading.Tasks.Task LogoutAdminAsync(UFO.Server.SessionToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthAccessBll/RequestSessionToken", ReplyAction="http://tempuri.org/IAuthAccessBll/RequestSessionTokenResponse")]
        UFO.Server.SessionToken RequestSessionToken(UFO.Server.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthAccessBll/RequestSessionToken", ReplyAction="http://tempuri.org/IAuthAccessBll/RequestSessionTokenResponse")]
        System.Threading.Tasks.Task<UFO.Server.SessionToken> RequestSessionTokenAsync(UFO.Server.User user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthAccessBllChannel : UFO.Server.IAuthAccessBll, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthAccessBllClient : System.ServiceModel.ClientBase<UFO.Server.IAuthAccessBll>, UFO.Server.IAuthAccessBll {
        
        public AuthAccessBllClient() {
        }
        
        public AuthAccessBllClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthAccessBllClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthAccessBllClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthAccessBllClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UFO.Server.User[] GetAll(UFO.Server.SessionToken token) {
            return base.Channel.GetAll(token);
        }
        
        public System.Threading.Tasks.Task<UFO.Server.User[]> GetAllAsync(UFO.Server.SessionToken token) {
            return base.Channel.GetAllAsync(token);
        }
        
        public bool IsUserAuthenticated(UFO.Server.SessionToken token) {
            return base.Channel.IsUserAuthenticated(token);
        }
        
        public System.Threading.Tasks.Task<bool> IsUserAuthenticatedAsync(UFO.Server.SessionToken token) {
            return base.Channel.IsUserAuthenticatedAsync(token);
        }
        
        public bool IsValidAdmin(UFO.Server.SessionToken token) {
            return base.Channel.IsValidAdmin(token);
        }
        
        public System.Threading.Tasks.Task<bool> IsValidAdminAsync(UFO.Server.SessionToken token) {
            return base.Channel.IsValidAdminAsync(token);
        }
        
        public bool LoginAdmin(UFO.Server.SessionToken token) {
            return base.Channel.LoginAdmin(token);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAdminAsync(UFO.Server.SessionToken token) {
            return base.Channel.LoginAdminAsync(token);
        }
        
        public void LogoutAdmin(UFO.Server.SessionToken token) {
            base.Channel.LogoutAdmin(token);
        }
        
        public System.Threading.Tasks.Task LogoutAdminAsync(UFO.Server.SessionToken token) {
            return base.Channel.LogoutAdminAsync(token);
        }
        
        public UFO.Server.SessionToken RequestSessionToken(UFO.Server.User user) {
            return base.Channel.RequestSessionToken(user);
        }
        
        public System.Threading.Tasks.Task<UFO.Server.SessionToken> RequestSessionTokenAsync(UFO.Server.User user) {
            return base.Channel.RequestSessionTokenAsync(user);
        }
    }
}
