//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UFO.Server {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private UFO.Server.Artist Artistk__BackingFieldField;
        
        private string EMailk__BackingFieldField;
        
        private string FirstNamek__BackingFieldField;
        
        private bool IsAdmink__BackingFieldField;
        
        private bool IsArtistk__BackingFieldField;
        
        private string LastNamek__BackingFieldField;
        
        private string Passwordk__BackingFieldField;
        
        private int UserIdk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Artist>k__BackingField", IsRequired=true)]
        public UFO.Server.Artist Artistk__BackingField {
            get {
                return this.Artistk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Artistk__BackingFieldField, value) != true)) {
                    this.Artistk__BackingFieldField = value;
                    this.RaisePropertyChanged("Artistk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<EMail>k__BackingField", IsRequired=true)]
        public string EMailk__BackingField {
            get {
                return this.EMailk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.EMailk__BackingFieldField, value) != true)) {
                    this.EMailk__BackingFieldField = value;
                    this.RaisePropertyChanged("EMailk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<FirstName>k__BackingField", IsRequired=true)]
        public string FirstNamek__BackingField {
            get {
                return this.FirstNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNamek__BackingFieldField, value) != true)) {
                    this.FirstNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("FirstNamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<IsAdmin>k__BackingField", IsRequired=true)]
        public bool IsAdmink__BackingField {
            get {
                return this.IsAdmink__BackingFieldField;
            }
            set {
                if ((this.IsAdmink__BackingFieldField.Equals(value) != true)) {
                    this.IsAdmink__BackingFieldField = value;
                    this.RaisePropertyChanged("IsAdmink__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<IsArtist>k__BackingField", IsRequired=true)]
        public bool IsArtistk__BackingField {
            get {
                return this.IsArtistk__BackingFieldField;
            }
            set {
                if ((this.IsArtistk__BackingFieldField.Equals(value) != true)) {
                    this.IsArtistk__BackingFieldField = value;
                    this.RaisePropertyChanged("IsArtistk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<LastName>k__BackingField", IsRequired=true)]
        public string LastNamek__BackingField {
            get {
                return this.LastNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNamek__BackingFieldField, value) != true)) {
                    this.LastNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("LastNamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Password>k__BackingField", IsRequired=true)]
        public string Passwordk__BackingField {
            get {
                return this.Passwordk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Passwordk__BackingFieldField, value) != true)) {
                    this.Passwordk__BackingFieldField = value;
                    this.RaisePropertyChanged("Passwordk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<UserId>k__BackingField", IsRequired=true)]
        public int UserIdk__BackingField {
            get {
                return this.UserIdk__BackingFieldField;
            }
            set {
                if ((this.UserIdk__BackingFieldField.Equals(value) != true)) {
                    this.UserIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("UserIdk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Artist", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class Artist : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ArtistIdk__BackingFieldField;
        
        private UFO.Server.Category Categoryk__BackingFieldField;
        
        private UFO.Server.Country Countryk__BackingFieldField;
        
        private string EMailk__BackingFieldField;
        
        private string Namek__BackingFieldField;
        
        private UFO.Server.BlobData Picturek__BackingFieldField;
        
        private string PromoVideok__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ArtistId>k__BackingField", IsRequired=true)]
        public int ArtistIdk__BackingField {
            get {
                return this.ArtistIdk__BackingFieldField;
            }
            set {
                if ((this.ArtistIdk__BackingFieldField.Equals(value) != true)) {
                    this.ArtistIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("ArtistIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Category>k__BackingField", IsRequired=true)]
        public UFO.Server.Category Categoryk__BackingField {
            get {
                return this.Categoryk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Categoryk__BackingFieldField, value) != true)) {
                    this.Categoryk__BackingFieldField = value;
                    this.RaisePropertyChanged("Categoryk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Country>k__BackingField", IsRequired=true)]
        public UFO.Server.Country Countryk__BackingField {
            get {
                return this.Countryk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Countryk__BackingFieldField, value) != true)) {
                    this.Countryk__BackingFieldField = value;
                    this.RaisePropertyChanged("Countryk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<EMail>k__BackingField", IsRequired=true)]
        public string EMailk__BackingField {
            get {
                return this.EMailk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.EMailk__BackingFieldField, value) != true)) {
                    this.EMailk__BackingFieldField = value;
                    this.RaisePropertyChanged("EMailk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Name>k__BackingField", IsRequired=true)]
        public string Namek__BackingField {
            get {
                return this.Namek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Namek__BackingFieldField, value) != true)) {
                    this.Namek__BackingFieldField = value;
                    this.RaisePropertyChanged("Namek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Picture>k__BackingField", IsRequired=true)]
        public UFO.Server.BlobData Picturek__BackingField {
            get {
                return this.Picturek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Picturek__BackingFieldField, value) != true)) {
                    this.Picturek__BackingFieldField = value;
                    this.RaisePropertyChanged("Picturek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<PromoVideo>k__BackingField", IsRequired=true)]
        public string PromoVideok__BackingField {
            get {
                return this.PromoVideok__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.PromoVideok__BackingFieldField, value) != true)) {
                    this.PromoVideok__BackingFieldField = value;
                    this.RaisePropertyChanged("PromoVideok__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CategoryIdk__BackingFieldField;
        
        private string Namek__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CategoryId>k__BackingField", IsRequired=true)]
        public string CategoryIdk__BackingField {
            get {
                return this.CategoryIdk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryIdk__BackingFieldField, value) != true)) {
                    this.CategoryIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("CategoryIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Name>k__BackingField", IsRequired=true)]
        public string Namek__BackingField {
            get {
                return this.Namek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Namek__BackingFieldField, value) != true)) {
                    this.Namek__BackingFieldField = value;
                    this.RaisePropertyChanged("Namek__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Country", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class Country : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string Codek__BackingFieldField;
        
        private string Namek__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Code>k__BackingField", IsRequired=true)]
        public string Codek__BackingField {
            get {
                return this.Codek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Codek__BackingFieldField, value) != true)) {
                    this.Codek__BackingFieldField = value;
                    this.RaisePropertyChanged("Codek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Name>k__BackingField", IsRequired=true)]
        public string Namek__BackingField {
            get {
                return this.Namek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Namek__BackingFieldField, value) != true)) {
                    this.Namek__BackingFieldField = value;
                    this.RaisePropertyChanged("Namek__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BlobData", Namespace="http://schemas.datacontract.org/2004/07/UFO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class BlobData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private byte[] DataStreamk__BackingFieldField;
        
        private string Namek__BackingFieldField;
        
        private string Pathk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DataStream>k__BackingField", IsRequired=true)]
        public byte[] DataStreamk__BackingField {
            get {
                return this.DataStreamk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.DataStreamk__BackingFieldField, value) != true)) {
                    this.DataStreamk__BackingFieldField = value;
                    this.RaisePropertyChanged("DataStreamk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Name>k__BackingField", IsRequired=true)]
        public string Namek__BackingField {
            get {
                return this.Namek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Namek__BackingFieldField, value) != true)) {
                    this.Namek__BackingFieldField = value;
                    this.RaisePropertyChanged("Namek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Path>k__BackingField", IsRequired=true)]
        public string Pathk__BackingField {
            get {
                return this.Pathk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Pathk__BackingFieldField, value) != true)) {
                    this.Pathk__BackingFieldField = value;
                    this.RaisePropertyChanged("Pathk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Server.IAuthAccessBll")]
    public interface IAuthAccessBll {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthAccessBll/GetAll", ReplyAction="http://tempuri.org/IAuthAccessBll/GetAllResponse")]
        UFO.Server.User[] GetAll(string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthAccessBll/GetAll", ReplyAction="http://tempuri.org/IAuthAccessBll/GetAllResponse")]
        System.Threading.Tasks.Task<UFO.Server.User[]> GetAllAsync(string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthAccessBll/IsUserAuthenticated", ReplyAction="http://tempuri.org/IAuthAccessBll/IsUserAuthenticatedResponse")]
        bool IsUserAuthenticated(string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthAccessBll/IsUserAuthenticated", ReplyAction="http://tempuri.org/IAuthAccessBll/IsUserAuthenticatedResponse")]
        System.Threading.Tasks.Task<bool> IsUserAuthenticatedAsync(string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthAccessBll/IsValidAdmin", ReplyAction="http://tempuri.org/IAuthAccessBll/IsValidAdminResponse")]
        bool IsValidAdmin(UFO.Server.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthAccessBll/IsValidAdmin", ReplyAction="http://tempuri.org/IAuthAccessBll/IsValidAdminResponse")]
        System.Threading.Tasks.Task<bool> IsValidAdminAsync(UFO.Server.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthAccessBll/LoginAdmin", ReplyAction="http://tempuri.org/IAuthAccessBll/LoginAdminResponse")]
        bool LoginAdmin(string sessionId, UFO.Server.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthAccessBll/LoginAdmin", ReplyAction="http://tempuri.org/IAuthAccessBll/LoginAdminResponse")]
        System.Threading.Tasks.Task<bool> LoginAdminAsync(string sessionId, UFO.Server.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthAccessBll/LoginAdminByMailAndPassword", ReplyAction="http://tempuri.org/IAuthAccessBll/LoginAdminByMailAndPasswordResponse")]
        bool LoginAdminByMailAndPassword(string sessionId, string email, string passwordHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthAccessBll/LoginAdminByMailAndPassword", ReplyAction="http://tempuri.org/IAuthAccessBll/LoginAdminByMailAndPasswordResponse")]
        System.Threading.Tasks.Task<bool> LoginAdminByMailAndPasswordAsync(string sessionId, string email, string passwordHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthAccessBll/LogoutAdmin", ReplyAction="http://tempuri.org/IAuthAccessBll/LogoutAdminResponse")]
        void LogoutAdmin(string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthAccessBll/LogoutAdmin", ReplyAction="http://tempuri.org/IAuthAccessBll/LogoutAdminResponse")]
        System.Threading.Tasks.Task LogoutAdminAsync(string sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthAccessBll/EncryptUserCredentials", ReplyAction="http://tempuri.org/IAuthAccessBll/EncryptUserCredentialsResponse")]
        UFO.Server.EncryptUserCredentialsResponse EncryptUserCredentials(UFO.Server.EncryptUserCredentialsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthAccessBll/EncryptUserCredentials", ReplyAction="http://tempuri.org/IAuthAccessBll/EncryptUserCredentialsResponse")]
        System.Threading.Tasks.Task<UFO.Server.EncryptUserCredentialsResponse> EncryptUserCredentialsAsync(UFO.Server.EncryptUserCredentialsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthAccessBll/RequestSessionId", ReplyAction="http://tempuri.org/IAuthAccessBll/RequestSessionIdResponse")]
        string RequestSessionId(UFO.Server.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthAccessBll/RequestSessionId", ReplyAction="http://tempuri.org/IAuthAccessBll/RequestSessionIdResponse")]
        System.Threading.Tasks.Task<string> RequestSessionIdAsync(UFO.Server.User user);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EncryptUserCredentials", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EncryptUserCredentialsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public UFO.Server.User user;
        
        public EncryptUserCredentialsRequest() {
        }
        
        public EncryptUserCredentialsRequest(UFO.Server.User user) {
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EncryptUserCredentialsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EncryptUserCredentialsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public UFO.Server.User user;
        
        public EncryptUserCredentialsResponse() {
        }
        
        public EncryptUserCredentialsResponse(UFO.Server.User user) {
            this.user = user;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthAccessBllChannel : UFO.Server.IAuthAccessBll, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthAccessBllClient : System.ServiceModel.ClientBase<UFO.Server.IAuthAccessBll>, UFO.Server.IAuthAccessBll {
        
        public AuthAccessBllClient() {
        }
        
        public AuthAccessBllClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthAccessBllClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthAccessBllClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthAccessBllClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UFO.Server.User[] GetAll(string sessionId) {
            return base.Channel.GetAll(sessionId);
        }
        
        public System.Threading.Tasks.Task<UFO.Server.User[]> GetAllAsync(string sessionId) {
            return base.Channel.GetAllAsync(sessionId);
        }
        
        public bool IsUserAuthenticated(string sessionId) {
            return base.Channel.IsUserAuthenticated(sessionId);
        }
        
        public System.Threading.Tasks.Task<bool> IsUserAuthenticatedAsync(string sessionId) {
            return base.Channel.IsUserAuthenticatedAsync(sessionId);
        }
        
        public bool IsValidAdmin(UFO.Server.User user) {
            return base.Channel.IsValidAdmin(user);
        }
        
        public System.Threading.Tasks.Task<bool> IsValidAdminAsync(UFO.Server.User user) {
            return base.Channel.IsValidAdminAsync(user);
        }
        
        public bool LoginAdmin(string sessionId, UFO.Server.User user) {
            return base.Channel.LoginAdmin(sessionId, user);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAdminAsync(string sessionId, UFO.Server.User user) {
            return base.Channel.LoginAdminAsync(sessionId, user);
        }
        
        public bool LoginAdminByMailAndPassword(string sessionId, string email, string passwordHash) {
            return base.Channel.LoginAdminByMailAndPassword(sessionId, email, passwordHash);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAdminByMailAndPasswordAsync(string sessionId, string email, string passwordHash) {
            return base.Channel.LoginAdminByMailAndPasswordAsync(sessionId, email, passwordHash);
        }
        
        public void LogoutAdmin(string sessionId) {
            base.Channel.LogoutAdmin(sessionId);
        }
        
        public System.Threading.Tasks.Task LogoutAdminAsync(string sessionId) {
            return base.Channel.LogoutAdminAsync(sessionId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UFO.Server.EncryptUserCredentialsResponse UFO.Server.IAuthAccessBll.EncryptUserCredentials(UFO.Server.EncryptUserCredentialsRequest request) {
            return base.Channel.EncryptUserCredentials(request);
        }
        
        public void EncryptUserCredentials(ref UFO.Server.User user) {
            UFO.Server.EncryptUserCredentialsRequest inValue = new UFO.Server.EncryptUserCredentialsRequest();
            inValue.user = user;
            UFO.Server.EncryptUserCredentialsResponse retVal = ((UFO.Server.IAuthAccessBll)(this)).EncryptUserCredentials(inValue);
            user = retVal.user;
        }
        
        public System.Threading.Tasks.Task<UFO.Server.EncryptUserCredentialsResponse> EncryptUserCredentialsAsync(UFO.Server.EncryptUserCredentialsRequest request) {
            return base.Channel.EncryptUserCredentialsAsync(request);
        }
        
        public string RequestSessionId(UFO.Server.User user) {
            return base.Channel.RequestSessionId(user);
        }
        
        public System.Threading.Tasks.Task<string> RequestSessionIdAsync(UFO.Server.User user) {
            return base.Channel.RequestSessionIdAsync(user);
        }
    }
}
